create table if not exists public.inquiries (
  id bigint generated by default as identity primary key,
  reference text unique not null,
  source text not null default 'ttt-website',
  inquiry_type text not null default 'general',
  topic text,
  first_name text not null,
  last_name text not null,
  email text not null,
  phone text,
  company text,
  message text not null,
  consent_at timestamptz not null default now(),
  created_at timestamptz not null default now()
);

alter table public.inquiries enable row level security;
revoke all on table public.inquiries from anon, authenticated;
grant insert, select on table public.inquiries to service_role;
grant usage, select on sequence public.inquiries_id_seq to service_role;

-- Website submissions are accepted only through the server-side route using service-role credentials.
