create table if not exists public.project_requests (
  id bigint generated by default as identity primary key,
  reference text unique not null,
  source text default 'ttt-website',
  type text not null,
  year text,
  make text,
  model text,
  trim text,
  vin text,
  services jsonb default '[]'::jsonb,
  priority text,
  budget text,
  timeline text,
  notes text,
  name text not null,
  email text not null,
  phone text,
  consent_at timestamptz,
  created_at timestamptz default now()
);

alter table public.project_requests add column if not exists consent_at timestamptz;
alter table public.project_requests enable row level security;
revoke all on table public.project_requests from anon, authenticated;
grant insert, select on table public.project_requests to service_role;
grant usage, select on sequence public.project_requests_id_seq to service_role;

-- Website submissions are accepted only through the server-side route using service-role credentials.


-- Tessa knowledge-gap feedback. Website writes only through the server-side route.
create table if not exists public.tessa_unanswered_questions (
  id bigint generated by default as identity primary key,
  question text not null,
  normalized_question text,
  page_path text,
  referrer text,
  knowledge_version text,
  status text not null default 'new' check (status in ('new','covered','ignored')),
  matched_intent_id text,
  created_at timestamptz not null default now(),
  reviewed_at timestamptz
);
alter table public.tessa_unanswered_questions enable row level security;
revoke all on table public.tessa_unanswered_questions from anon, authenticated;
grant insert, select, update on table public.tessa_unanswered_questions to service_role;
grant usage, select on sequence public.tessa_unanswered_questions_id_seq to service_role;
create index if not exists tessa_unanswered_status_created_idx on public.tessa_unanswered_questions(status, created_at desc);
create index if not exists tessa_unanswered_normalized_idx on public.tessa_unanswered_questions(normalized_question)
  where normalized_question is not null and normalized_question <> '';
