create table if not exists public.project_requests (
  id bigint generated by default as identity primary key,
  reference text unique not null,
  source text default 'ttt-website',
  type text not null,
  year text,
  make text,
  model text,
  trim text,
  vin text,
  services jsonb default '[]'::jsonb,
  priority text,
  budget text,
  timeline text,
  notes text,
  name text not null,
  email text not null,
  phone text,
  created_at timestamptz default now()
);
alter table public.project_requests enable row level security;
-- No anonymous insert policy is required: website submissions use the server-side service role route.
