create table if not exists public.project_requests (
  id bigint generated by default as identity primary key,
  reference text unique not null,
  source text default 'ttt-website',
  type text not null,
  year text,
  make text,
  model text,
  trim text,
  vin text,
  services jsonb default '[]'::jsonb,
  priority text,
  budget text,
  timeline text,
  notes text,
  name text not null,
  email text not null,
  phone text,
  consent_at timestamptz,
  created_at timestamptz default now()
);

alter table public.project_requests add column if not exists consent_at timestamptz;
alter table public.project_requests enable row level security;
revoke all on table public.project_requests from anon, authenticated;
grant insert, select on table public.project_requests to service_role;
grant usage, select on sequence public.project_requests_id_seq to service_role;

-- Website submissions are accepted only through the server-side route using service-role credentials.
