import Link from 'next/link';
import ServiceIcon from '../../components/ServiceIcon';
import TessaTrigger from '../../components/TessaTrigger';
import { getPageCopy } from '../../lib/sanityContent';

const fallbackServices=[
 {icon:'tint',title:'Window Tint',meta:'Cooler cabin. Less glare. More privacy.',bullets:['Heat and glare on daily drives','Protecting seats and trim from UV','Privacy for passengers and belongings'],href:'/services/window-tint'},
 {icon:'audio',title:'Automotive Audio',meta:'Better sound built around how you listen.',bullets:['Factory systems that sound flat or distort','Adding bass without losing the trunk','Keeping CarPlay, steering controls and chimes'],href:'/services/audio'},
 {icon:'gps',title:'GPS Tracking',meta:'Know where the vehicle is.',bullets:['Theft response and recovery support','Family and stored vehicles','Work trucks and small fleets'],href:'/services/gps-tracking'},
 {icon:'security',title:'Kill Switches',meta:'Make unauthorized use harder.',bullets:['Frequently targeted models','Street or open-lot parking','An extra layer beyond factory security'],href:'/services/kill-switches'},
 {icon:'signal',title:'TTT SignalTrace™',meta:'Find the cause of the electrical problem.',bullets:['Batteries that keep going flat','Faults that come and go','Problems that started after other work'],href:'/services/signaltrace'},
 {icon:'fabrication',title:'Custom Fabrication',meta:'Make the part that doesn’t exist.',bullets:['Mounts, brackets and adapters','Switch panels and enclosures','Replacing hard-to-find trim pieces'],href:'/services/custom-fabrication'}
];
export async function generateMetadata(){const p=await getPageCopy('/services');return {title:p?.seoTitle||'Vehicle Technology Services in Houston | TTT',description:p?.seoDescription||'Window tint, audio, GPS tracking, kill switches, SignalTrace electrical diagnostics and custom fabrication for modern vehicles in Houston.'}}
export default async function Page(){const cms=await getPageCopy('/services');const c=(k,f)=>cms?.copy?.[k]||f;const services=cms?.collections?.services?.length?cms.collections.services:fallbackServices;const standards=cms?.collections?.standard||[];return <main className="production-page"><section className="page-hero page-hero--review"><div className="shell"><p className="eyebrow">{c('hero.eyebrow','What we do to the vehicle')}</p><h1>{c('hero.title','Services')}</h1><p className="lead">{c('hero.lead','Six kinds of work on modern vehicles. Each one is planned around the systems already in the car and checked before it goes back to you.')}</p><div className="button-row"><Link className="button" href="/quote">Request a Quote →</Link><Link className="button button--ghost" href="/solutions">Start from an outcome instead →</Link></div></div></section><section className="section"><div className="shell"><div className="service-card-grid service-card-grid--large">{services.map(item=><Link href={item.href} className="service-card-production" key={item.title}><ServiceIcon name={item.icon}/><h2>{item.title}</h2><strong>{item.meta}</strong><ul>{(item.bullets||[]).map(x=><li key={x}>{x}</li>)}</ul><b>See {item.title} →</b></Link>)}</div></div></section><section className="section section--soft"><div className="shell copy-section__grid"><div><p className="eyebrow">{c('standard.eyebrow','The TTT Standard')}</p><h2>{c('standard.title','The same standard on every job.')}</h2></div><div className="copy-section__body"><ul className="clean-list">{(standards.length?standards:[{body:'It works with the car. We check what the new work could affect before we start.'},{body:'You approve the scope. Changes are discussed before they are added.'},{body:'Finished means checked. We test the work and the systems it touched, then show you what changed.'}]).map(item=><li key={item.body}>{item.body}</li>)}</ul><Link className="text-link" href="/standards">Read The TTT Standard →</Link></div></div></section><section className="cta-band"><div className="shell cta-band__inner"><div><p className="eyebrow">{c('closing.eyebrow','Not sure which service?')}</p><h2>{c('closing.title','Describe the problem instead.')}</h2><p>{c('closing.body','Many jobs combine more than one service. Tell us what you want the vehicle to do, or what it is doing wrong, and we will recommend a starting point.')}</p><TessaTrigger className="text-link text-link--light" prompt="Which service do I need?">Ask Tessa: “Which service do I need?” →</TessaTrigger></div><div className="button-row"><Link className="button button--light" href="/quote">Request a Quote →</Link><Link className="text-link text-link--light" href="/solutions">Browse Solutions →</Link></div></div></section></main>}
