import Link from 'next/link';
import AssetMedia from '../../components/AssetMedia';

export const metadata={title:'About Thompson Transportation Technologies | TTT',description:'TTT is a Houston automotive technology company focused on careful installation, correct integration and verified results. Meet the partners and learn how the company works.'};

const partners=[
  {name:'Derek Thompson',focus:'Vehicle Integration & Customer Experience',image:'/team/derek-thompson.webp',bio:'Derek brings the hands-on automotive installation perspective to TTT. His focus is how work is scoped, fitted, executed and handed back to the customer so the finished vehicle is practical, serviceable and complete.'},
  {name:'Kevin Yap',focus:'Strategy, Systems & Growth',image:'/team/kevin-yap.webp',bio:'Kevin focuses on business strategy, digital systems and growth: connecting the website, customer workflow, pricing, data and TTT-OS so the company can scale beyond one-off installations.'},
  {name:'Amjad Kharoof',focus:'Products, Sourcing & Operations',image:'/team/amjad-kharoof.webp',bio:'Amjad focuses on the product and operational side of TTT: equipment, supplier options, pricing inputs and repeatable workflows that help turn good recommendations into work the team can deliver consistently.'}
];

export default function Page(){return <main className="production-page">
 <section className="review-hero review-hero--compact"><AssetMedia visual="workshopReal" className="review-hero__media" priority/><div className="review-hero__overlay"/><div className="shell review-hero__copy"><p className="eyebrow">About TTT</p><h1>About Thompson Transportation Technologies</h1><p className="review-hero__theme">We treat vehicle work as technical work.</p><p className="lead lead--dark">TTT is a Houston company that installs, integrates, diagnoses and fabricates for modern vehicles, with the planning and testing that kind of work deserves.</p><div className="button-row"><Link className="button" href="/quote">Request a Quote →</Link><Link className="button button--ghost-dark" href="/concept-one">Explore Concept One</Link></div></div></section>
 <section className="section"><div className="shell copy-section__grid"><div><p className="eyebrow">Who we are</p><h2>An automotive technology company</h2></div><div className="copy-section__body"><p>Thompson Transportation Technologies works on the systems that make modern vehicles more comfortable, more secure and more capable: window film, audio, tracking, immobilization, electrical diagnostics and custom-made parts.</p><p>What connects those services is the way we approach them. Every job is treated as an integration problem, because every addition affects something else in the vehicle.</p></div></div></section>
 <section className="section section--soft"><div className="shell"><div className="section-heading"><div><p className="eyebrow">The partners</p><h2>Three perspectives behind one operating standard.</h2><p className="lead">TTT combines hands-on vehicle integration, product and operational discipline, and the systems needed to build a scalable automotive technology company.</p></div></div><div className="partner-grid">{partners.map(({name,focus,image,bio})=><article className="partner-card" key={name}><img className="partner-card__portrait" src={image} alt={name} width="800" height="800" loading="lazy"/><div><p className="partner-card__focus">{focus}</p><h3>{name}</h3><p>{bio}</p></div></article>)}</div></div></section>
 <section className="section"><div className="shell editorial-media-band"><AssetMedia visual="diagnosticReal"/><div><p className="eyebrow">Why TTT exists</p><h2>Vehicles changed. Much of the work did not.</h2><p>Vehicles now rely on networks of modules, sensors and software. Aftermarket work cannot be treated as a collection of isolated wires and boxes. The system has to be understood first, integrated properly and verified after the work is complete.</p></div></div></section>
 <section className="section section--dark"><div className="shell"><div className="section-heading"><div><p className="eyebrow">How we think</p><h2>Four principles behind the work</h2></div></div><div className="principle-grid"><article><small>01</small><h3>Installation quality is mostly hidden.</h3><p>Routing, connections, protection from heat and movement, and service access matter long after trim panels go back on.</p></article><article><small>02</small><h3>Integration means the whole vehicle still works.</h3><p>Adding something new should not break something old. Factory features and related systems are checked before and after work.</p></article><article><small>03</small><h3>Testing is part of the job.</h3><p>Installation and repair are not finished until the relevant systems are verified.</p></article><article><small>04</small><h3>When the answer is not obvious, investigate.</h3><p>That mindset shaped SignalTrace and carries through the rest of the work.</p></article></div></div></section>
 <section className="section"><div className="shell editorial-media-band editorial-media-band--reverse"><AssetMedia visual="houstonDusk"/><div><p className="eyebrow">Houston</p><h2>Based in Houston</h2><p>Houston heat, long drives and demanding day-to-day use put real pressure on vehicle interiors, electronics and installed systems. TTT’s service mix is shaped around those conditions.</p></div></div></section>
 <section className="cta-band"><div className="shell cta-band__inner"><div><p className="eyebrow">About TTT</p><h2>Let’s talk about your vehicle.</h2></div><Link className="button button--light" href="/quote">Request a Quote →</Link></div></section>
 </main>}
