import Link from 'next/link';
export const metadata={title:'OEM Vehicle Technology Integration | TTT',description:'How TTT approaches factory controls, data networks, warning tones, cameras and modern electronics when adding aftermarket technology.'};
export default function Page(){return <main className="production-page">
 <section className="page-hero page-hero--review"><div className="shell"><p className="eyebrow">Learn / Technology / OEM Integration</p><h1>The vehicle is already a system before the first aftermarket part goes in.</h1><p className="lead">Screens, controls, cameras, alerts and data can all be connected. Good integration starts with what must stay working.</p></div></section>
 <section className="section"><div className="shell copy-section__grid"><div><p className="eyebrow">Preserve first</p><h2>Upgrade capability without casually removing useful OEM behavior.</h2></div><div className="copy-section__body"><p>Steering-wheel controls, warning tones, microphones, factory cameras, parking sensors and vehicle settings may depend on the original architecture.</p></div></div></section>
 <section className="section section--soft"><div className="shell principle-grid"><article><small>01 / CONTROLS</small><h3>Keep the interfaces that still make sense.</h3><p>Screen, steering controls and physical inputs.</p></article><article><small>02 / ALERTS</small><h3>Know what the vehicle is trying to tell you.</h3><p>Chimes, sensors, warnings and cameras.</p></article><article><small>03 / SERVICE</small><h3>Leave a path for diagnosis later.</h3><p>Access, documentation and reversibility.</p></article></div></section>
 <section className="section section--dark"><div className="shell"><div className="diagram-panel"><div className="diagram-panel__head"><div><p className="eyebrow">Integration path</p><h2>Retain → interface → add capability.</h2></div><p>The exact path changes by year, make, model, trim and software. The principle does not.</p></div><div className="technical-flow"><div className="flow-node"><small>01</small><strong>Factory system</strong><em>→</em></div><div className="flow-node"><small>02</small><strong>What stays</strong><em>→</em></div><div className="flow-node"><small>03</small><strong>Interface</strong><em>→</em></div><div className="flow-node"><small>04</small><strong>Added system</strong><em>→</em></div><div className="flow-node"><small>05</small><strong>Validate</strong></div></div></div></div></section>
 <section className="cta-band"><div className="shell cta-band__inner"><div><p className="eyebrow">OEM integration</p><h2>Preserve what works. Improve what matters.</h2></div><Link className="button button--light" href="/articles">Read TTT Articles →</Link></div></section>
 </main>}
