import Link from 'next/link';
export const metadata={title:'Privacy Policy',description:'Privacy Policy for Thompson Transportation Technologies LLC.'};
const updated='September 10, 2026';
export default function Page(){return <main className="legal-page"><section className="legal-hero"><div className="shell shell--legal"><p className="eyebrow">Legal</p><h1>Privacy Policy</h1><p className="lead">How Thompson Transportation Technologies LLC handles personal information across its website, project intake, customer relationships and connected services.</p><p className="legal-updated">Last updated: {updated}</p></div></section><section className="section"><div className="shell shell--legal legal-copy">
  <h2>1. Scope</h2><p>This Privacy Policy describes how Thompson Transportation Technologies LLC (“TTT,” “we,” “us,” or “our”) collects, uses, discloses and protects personal information when you visit our website, submit an inquiry or project request, purchase or request products or services, create or use a TTT account, communicate with us, or use other services that link to this Policy. Some third-party products and platforms may have their own privacy notices.</p>
  <h2>2. Information we may collect</h2><p>Depending on how you interact with TTT, we may collect identifiers and contact information such as name, email, phone number, mailing or billing address and account identifiers; vehicle information such as year, make, model, trim, VIN, photos, installed equipment and service history; project and commercial information such as requested services, estimates, orders, appointment details, warranty records and support history; communications and content you submit; and technical information such as IP address, browser/device information, referring pages, site activity and timestamps collected through our hosting, security and analytics systems.</p><p>If you request connected vehicle, tracking or telematics services, the relevant service may process location or precise geolocation information. TTT will use such information only for the service, support, security or other purposes disclosed to you, and will seek consent where required. We do not intentionally collect biometric identifiers unless a separately disclosed feature requires them.</p>
  <h2>3. Sources of information</h2><p>We collect information directly from you; from authorized dealership, fleet or business representatives; automatically through our website and service providers; from products or platforms you authorize us to integrate; and from vendors, manufacturers or other partners when needed to fulfill a transaction, warranty or support request.</p>
  <h2>4. How we use information</h2><p>We may use personal information to respond to inquiries; prepare estimates and project scopes; schedule and perform services; verify fitment and vehicle details; manage orders, payments, shipping, warranties and support; operate My TTT and other account features; provide connected or telematics services you request; communicate transactional information; improve our website, products, services and security; detect misuse or fraud; maintain business records; comply with law; and, where permitted, send marketing communications you can opt out of.</p>
  <h2>5. How we disclose information</h2><p>We may disclose information to service providers that support hosting, cybersecurity, analytics, authentication, CRM, communications, scheduling, ecommerce, payments, shipping, data storage and customer support; to product manufacturers, distributors or warranty providers when needed for fulfillment or support; to dealership or fleet organizations where you are an authorized member; to professional advisers; in connection with a business transaction; and when required or permitted by law. We require service providers to handle information for appropriate business purposes and expect them to apply suitable safeguards.</p>
  <h2>6. Sale, targeted advertising and sensitive data</h2><p>TTT does not sell personal information for money. We do not knowingly sell sensitive personal data or biometric data. If our practices later constitute a “sale” or targeted advertising under an applicable state privacy law, we will provide the required disclosure and opt-out mechanism before using data in that manner. We do not use precise geolocation for unrelated advertising purposes.</p>
  <h2>7. Cookies, analytics and similar technologies</h2><p>Our website and providers may use cookies, local storage, pixels, logs and similar technologies that are necessary for site functionality, security, preferences, measurement and analytics. When legally required, we will provide choices for non-essential technologies. Browser controls may also allow you to delete or block cookies, although doing so can affect site features.</p>
  <h2>8. Data minimization, retention and security</h2><p>We aim to collect information that is adequate, relevant and reasonably necessary for disclosed purposes. Retention varies by purpose, including project history, warranty, tax/accounting, dispute, security and legal requirements. We use administrative, technical and physical safeguards appropriate to the nature of the data, but no network, storage system or transmission is guaranteed to be completely secure.</p>
  <h2>9. Your privacy choices and rights</h2><p>You may opt out of non-transactional marketing using the unsubscribe method provided in the message. Depending on where you live and whether a privacy law applies to TTT, you may also have rights to confirm processing, access, correct, delete or obtain a copy of personal data, and to opt out of certain targeted advertising, sale or profiling. We will not unlawfully discriminate against you for exercising applicable privacy rights.</p><p>Texas residents may have rights under the Texas Data Privacy and Security Act, including access, correction, deletion, data portability and opt-out rights for certain processing. Requests should not require you to create a new account solely to exercise a privacy right. You may also have a right to appeal a denied request where applicable.</p>
  <h2>10. How to submit a privacy request</h2><p>Use our <Link href="/contact">Contact page</Link> and select “Privacy request.” We may need to verify your identity and authority before fulfilling a request. Authorized agents may submit requests where permitted by law. The online request channel will be connected to TTT's production privacy/CRM workflow before commercial launch.</p>
  <h2>11. Children</h2><p>TTT's services are not directed to children under 13, and we do not knowingly collect personal information from children under 13 through the website. If we learn that such information was collected without appropriate authorization, we will take reasonable steps to delete it. Connected products used by families may be subject to separate manufacturer terms and privacy notices.</p>
  <h2>12. Third-party services and links</h2><p>Our site may link to or integrate services operated by manufacturers, ecommerce providers, payment processors, mapping/telematics providers, social networks or other third parties. Their privacy practices are governed by their own notices, not this Policy.</p>
  <h2>13. Changes to this Policy</h2><p>We may update this Policy as TTT services, technologies or legal requirements change. We will post the revised Policy and update the “Last updated” date. We will provide additional notice when required by law.</p>
  <h2>14. Contact</h2><p>Questions about this Policy or TTT privacy practices can be submitted through the <Link href="/contact">Contact page</Link>. A dedicated privacy email and mailing address will be added once TTT's production contact infrastructure is finalized.</p>
  <div className="legal-source-note"><h2>Legal framework used for this draft</h2><p>This policy was researched against the Texas Data Privacy and Security Act (Texas Business & Commerce Code Chapter 541), Texas Attorney General/DIR guidance, and FTC privacy and data-security guidance. It is intended to reflect TTT's planned operating model and should be reviewed whenever analytics, advertising, ecommerce, telematics, CRM or other data flows materially change.</p></div>
</div></section></main>}
