import './globals.css';
import './phase2.css';
import './refinement.css';
import './wave2.css';
import './logo-fix.css';
import './logo-polish.css';
import './editorial.css';
import './visuals.css';
import './premium.css';
import './cinematic.css';
import './cinematic-mobile.css';
import './launch-hardening.css';
import './agency-pass.css';
import './home-refinement.css';
import './tessa.css';
import './production-review.css';
import './wave1-content.css';
import './wave1-5.css';
import './wave2-interactive.css';
import './wave2b.css';
import './wave2c.css';
import './wave2d.css';
import './wave2e.css';
import './wave3a.css';
import './wave3b.css';
import './wave3c.css';
import './wave3d.css';
import './wave3e.css';
import './wave3f.css';
import './wave3h.css';
import './wave3i.css';
import './wave3j.css';
import './wave3k.css';
import './wave3l.css';
import './wave3m.css';
import './wave3n.css';
import './wave3o.css';
import './wave3p.css';
import './wave3q.css';
import './wave3r.css';
import './wave3s.css';
import './production-fusion.css';
import './production-mobile.css';
import SiteHeader from '../components/SiteHeader';
import SiteFooter from '../components/SiteFooter';
import SiteTelemetry from '../components/SiteTelemetry';
import TessaAssistant from '../components/TessaAssistant';
import { TTTBuildProvider } from '../components/wave2/TTTBuildContext';
import BuildDock from '../components/wave2/BuildDock';
import { organizationSchema, siteDescription, siteName, siteUrl } from '../lib/siteConfig';
import { getSingleton } from '../lib/sanityContent';
const shareImage='https://d8j0ntlcm91z4.cloudfront.net/user_3J1GdLYiOgasiASmq5JnzF6gb6O/hf_20260930_020500_436f440d-9326-4545-a2be-d8cc9b48792c.png';
export async function generateMetadata(){const settings=await getSingleton('siteSettings');const name=settings?.businessName||siteName;const short=settings?.shortName||'TTT';const description=settings?.siteDescription||siteDescription;return {applicationName:short,title:{default:short+' — '+name,template:'%s'},description,metadataBase:new URL(siteUrl),appleWebApp:{capable:true,title:short,statusBarStyle:'default'},openGraph:{title:short+' — '+name,description,url:siteUrl,type:'website',siteName:name,locale:'en_US',images:[{url:shareImage,width:1536,height:1024,alt:name+' — premium automotive technology'}]},twitter:{card:'summary_large_image',title:short+' — '+name,description,images:[shareImage]}};}
export const viewport={width:'device-width',initialScale:1,viewportFit:'cover',themeColor:'#0d0f14'};
export default async function RootLayout({children}){const settings=await getSingleton('siteSettings');const schema={...organizationSchema,name:settings?.businessName||organizationSchema.name,alternateName:settings?.shortName||organizationSchema.alternateName,description:settings?.siteDescription||organizationSchema.description,areaServed:{'@type':'AdministrativeArea',name:settings?.primaryMarket||organizationSchema.areaServed?.name||'Greater Houston'}};return <html lang="en"><body><script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(schema)}}/><a className="skip-link" href="#main-content">Skip to main content</a><TTTBuildProvider><SiteHeader/><div id="main-content">{children}</div><SiteFooter/><TessaAssistant/><BuildDock/><SiteTelemetry/></TTTBuildProvider></body></html>}