import Link from 'next/link';
import WebsiteVisual from './WebsiteVisual';

const copy={
  audio:{eyebrow:'Automotive Audio',title:'Car audio built around how you listen',summary:'Clearer vocals, tighter bass, sound that fills the cabin evenly. We plan, install and tune audio systems that work with your vehicle instead of around it.',cta:'Request an Audio Quote',variant:'audio',intro:'Good audio starts with a conversation, not a parts list. Someone who wants podcasts to sound clear on the highway needs something very different from someone who wants bass they can feel.',headline:'What do you want to hear?'},
  tracking:{eyebrow:'GPS Tracking',title:'Know where your vehicle is',summary:'Professionally installed GPS tracking gives you location, alerts and history for one vehicle or several, fitted discreetly and powered reliably.',cta:'Request a Tracking Quote',variant:'tracking',intro:'Most of the time, a tracker sits quietly in the background. Its value shows up in specific moments: a vehicle that is not where it should be, a family vehicle running late, or a work truck that needs to be at a job site.',headline:'Visibility when you need it'},
  security:{eyebrow:'Kill Switches',title:'An added layer of control over who drives your vehicle',summary:'A professionally integrated immobilization solution makes your vehicle harder to start without your authorization, and works alongside the security you already have.',cta:'Request a Security Consultation',variant:'security',intro:'A kill switch, or immobilization solution, prevents the vehicle from starting or running unless an authorized condition is met. An aftermarket solution adds an independent layer on top of factory security.',headline:'What a kill switch does'}
};

export default function DetailPage({item,kind}){
 const c=copy[item.slug]||{eyebrow:item.eyebrow,title:item.title,summary:item.summary,cta:item.cta||'Request a Quote',variant:item.slug,intro:(item.overview||[])[0]||item.summary,headline:'Designed around the vehicle, not around a box.'};
 const points=(item.points||[]).slice(0,6);
 const outcomes=(item.outcomes||[]).slice(0,4);
 return <main>
   <section className="asset-hero asset-hero--detail"><WebsiteVisual variant={c.variant} alt="" /><div className="asset-hero__shade"/><div className="shell asset-hero__copy"><p className="eyebrow">{c.eyebrow}</p><h1>{c.title}</h1><p className="lead lead--dark">{c.summary}</p><div className="button-row"><Link className="button" href={`/quote?service=${item.slug}`}>{c.cta}</Link><Link className="button button--ghost-dark" href="/services">All Services</Link></div></div></section>
   <section className="section"><div className="shell section-intro-grid"><div><p className="eyebrow">Start with the goal</p><h2>{c.headline}</h2></div><div className="section-copy"><p>{c.intro}</p>{(item.overview||[]).slice(1,2).map(x=><p key={x}>{x}</p>)}</div></div></section>
   <section className="section section--soft"><div className="shell"><div className="section-heading"><div><p className="eyebrow">What goes into the recommendation</p><h2>The system matters more than the parts list.</h2></div></div><div className="visual-stat-strip">{points.slice(0,3).map((p,i)=><div className="visual-stat" key={p.title||p}><small>0{i+1}</small><strong>{p.title||p}</strong><p>{typeof p==='string'?'Planned around the vehicle and goal.':p.body}</p></div>)}</div>{points.length>3?<div className="visual-stat-strip">{points.slice(3,6).map((p,i)=><div className="visual-stat" key={p.title||p}><small>0{i+4}</small><strong>{p.title||p}</strong><p>{typeof p==='string'?'Planned around the vehicle and goal.':p.body}</p></div>)}</div>:null}</div></section>
   <section className="section"><div className="shell editorial-visual-band"><WebsiteVisual variant={c.variant} alt="" /><div className="editorial-visual-copy"><p className="eyebrow">TTT standard</p><h2>Plan the integration before the installation.</h2>{outcomes.slice(0,3).map(x=><p key={x}>{x}</p>)}<Link className="button button--ghost" href={`/quote?service=${item.slug}`}>Discuss this vehicle →</Link></div></div></section>
   <section className="cta-band"><div className="shell"><h2>{c.cta}.</h2><Link className="button button--light" href={`/quote?service=${item.slug}`}>Start with the vehicle →</Link></div></section>
 </main>
}
