'use client';
import { useMemo, useState } from 'react';
import VehicleSelector from './VehicleSelector';

const steps=['Project','Vehicle','Goals','Priorities','Budget','Contact','Review'];
const serviceOptions=['Audio','Window tint','Security','Tracking','Cameras','Lighting','Electronics','Custom integration'];
const initial={type:'',year:'',make:'',model:'',trim:'',vin:'',services:[],priority:'',budget:'',timeline:'',notes:'',name:'',email:'',phone:'',consent:false,website:''};

export default function ProjectIntakeForm(){
 const [step,setStep]=useState(0); const [form,setForm]=useState(initial); const [error,setError]=useState(''); const [result,setResult]=useState(null); const [sending,setSending]=useState(false);
 const progress=useMemo(()=>((step+1)/steps.length)*100,[step]); const update=(k,v)=>setForm(c=>({...c,[k]:v})); const toggle=v=>update('services',form.services.includes(v)?form.services.filter(x=>x!==v):[...form.services,v]);
 const valid=()=>{if(step===0&&!form.type)return 'Choose a project type.';if(step===2&&!form.services.length)return 'Choose at least one system.';if(step===5&&(!form.name||!form.email))return 'Name and email are required.';if(step===5&&!form.consent)return 'Please confirm that TTT may use these details to respond to your project request.';return ''};
 const next=()=>{const e=valid();setError(e);if(!e)setStep(s=>Math.min(steps.length-1,s+1))};
 const submit=async()=>{setSending(true);setError('');try{const r=await fetch('/api/project-request',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(form)});const j=await r.json();if(!r.ok)throw new Error(j.error||'Unable to submit');setResult(j);}catch(e){setError(e.message)}finally{setSending(false)}};
 if(result)return <div className="intake-success"><p className="eyebrow">Project request received</p><h2>{result.reference}</h2><p>Your project request has been routed to TTT. Keep this reference for follow-up.</p><div className="button-row"><a className="button" href="/">Return home</a><button className="button button--ghost" onClick={()=>{setForm(initial);setStep(0);setResult(null)}}>Start another</button></div></div>;
 return <div className="intake"><div className="intake__top"><span>Step {step+1} of {steps.length}</span><strong>{steps[step]}</strong></div><div className="progress"><span style={{width:`${progress}%`}}/></div>
 {step===0&&<div className="intake__panel"><p className="eyebrow">What are we building?</p><h2>Choose the kind of project.</h2><div className="choice-grid">{['Personal vehicle','Dealership','Fleet','Commercial vehicle','Other'].map(x=><button key={x} className={form.type===x?'choice is-selected':'choice'} onClick={()=>update('type',x)}>{x}<span>→</span></button>)}</div></div>}
 {step===1&&<div className="intake__panel"><p className="eyebrow">Vehicle</p><h2>Tell us what we are working with.</h2><VehicleSelector compact onChange={v=>setForm(c=>({...c,...v}))}/><div className="field-grid field-grid--2"><label>VIN (optional)<input value={form.vin} onChange={e=>update('vin',e.target.value.toUpperCase())} placeholder="17-character VIN"/></label><label>Timeline<input value={form.timeline} onChange={e=>update('timeline',e.target.value)} placeholder="e.g. Within 30 days"/></label></div></div>}
 {step===2&&<div className="intake__panel"><p className="eyebrow">Systems</p><h2>What do you want to improve?</h2><div className="choice-grid">{serviceOptions.map(x=><button key={x} className={form.services.includes(x)?'choice is-selected':'choice'} onClick={()=>toggle(x)}>{x}<span>{form.services.includes(x)?'✓':'+'}</span></button>)}</div></div>}
 {step===3&&<div className="intake__panel"><p className="eyebrow">Priority</p><h2>What matters most?</h2><div className="choice-grid">{['Sound quality','Security','Factory appearance','Privacy','Technology','Value','Show / custom'].map(x=><button key={x} className={form.priority===x?'choice is-selected':'choice'} onClick={()=>update('priority',x)}>{x}<span>→</span></button>)}</div></div>}
 {step===4&&<div className="intake__panel"><p className="eyebrow">Investment</p><h2>What budget range should we design around?</h2><div className="choice-grid">{['Under $1,000','$1,000–$2,500','$2,500–$5,000','$5,000–$10,000','$10,000+','Not sure'].map(x=><button key={x} className={form.budget===x?'choice is-selected':'choice'} onClick={()=>update('budget',x)}>{x}<span>→</span></button>)}</div></div>}
 {step===5&&<div className="intake__panel"><p className="eyebrow">Contact</p><h2>Where should TTT reach you?</h2><div className="field-grid"><label>Name *<input value={form.name} onChange={e=>update('name',e.target.value)} placeholder="Your name"/></label><label>Email *<input type="email" value={form.email} onChange={e=>update('email',e.target.value)} placeholder="you@example.com"/></label><label>Phone<input value={form.phone} onChange={e=>update('phone',e.target.value)} placeholder="(555) 555-5555"/></label></div><label style={{display:'flex',flexDirection:'column',gap:8,marginTop:20,fontSize:12,fontWeight:700}}>Project notes<textarea value={form.notes} onChange={e=>update('notes',e.target.value)} placeholder="Anything TTT should know about the vehicle, desired outcome, existing equipment or constraints?"/></label><label className="consent-check" style={{marginTop:20}}><input type="checkbox" checked={form.consent} onChange={e=>update('consent',e.target.checked)}/><span>I agree that TTT may use the information I submit to respond to this project request. See the <a href="/privacy">Privacy Policy</a>.</span></label><label aria-hidden="true" style={{position:'absolute',left:'-10000px',width:1,height:1,overflow:'hidden'}}>Website<input tabIndex="-1" autoComplete="off" value={form.website} onChange={e=>update('website',e.target.value)}/></label></div>}
 {step===6&&<div className="intake__panel"><p className="eyebrow">Review</p><h2>Confirm your TTT project brief.</h2><div className="intake-review"><div><span>Project</span><strong>{form.type}</strong></div><div><span>Vehicle</span><strong>{[form.year,form.make,form.model,form.trim].filter(Boolean).join(' ')||'Not specified'}</strong></div><div><span>Systems</span><strong>{form.services.join(', ')}</strong></div><div><span>Priority</span><strong>{form.priority||'Not specified'}</strong></div><div><span>Budget</span><strong>{form.budget||'Not specified'}</strong></div><div><span>Contact</span><strong>{form.name} · {form.email}</strong></div></div><p className="save-note">Submitting sends this project brief to TTT and creates a reference for follow-up.</p></div>}
 {error&&<p className="validation-note" role="alert" style={{padding:'0 28px'}}>{error}</p>}<div className="intake__actions"><button className="button button--ghost" disabled={step===0||sending} onClick={()=>{setError('');setStep(s=>Math.max(0,s-1))}}>Back</button>{step===steps.length-1?<button className="button" disabled={sending} onClick={submit}>{sending?'Submitting…':'Submit project →'}</button>:<button className="button" onClick={next}>Continue →</button>}</div></div>
}
