import Link from 'next/link';
export const metadata={title:'Brands & Technology Partners | TTT',description:'How TTT evaluates automotive audio, security, tracking, cameras, film and vehicle electronics.'};
const categories=['Audio & DSP','Security','Tracking & telematics','Vehicle vision','Glass & film','Electronics & integration'];
const criteria=['Vehicle fit','Reliability','Documentation','Installer support','Warranty / RMA','Customer value'];
export default function Page(){return <main className="production-page">
 <section className="page-hero page-hero--review"><div className="shell"><p className="eyebrow">Learn / Technology / Brands</p><h1>Choose the product for the system, not the logo on the box.</h1><p className="lead">Fit, support, documentation and lifecycle matter as much as the feature list.</p></div></section>
 <section className="section"><div className="shell"><div className="section-heading"><div><p className="eyebrow">Technology categories</p><h2>Organized around what the product has to do.</h2><p>TTT evaluates products against the vehicle and use case first. Brand authorization or dealer status is published only when verified.</p></div></div><div className="technology-card-grid">{categories.map((title,i)=><article className="technology-card" key={title}><small>{String(i+1).padStart(2,'0')}</small><h3>{title}</h3><p>Evaluated for integration, support and the role it plays in the finished system.</p></article>)}</div></div></section>
 <section className="section section--soft"><div className="shell copy-section__grid"><div><p className="eyebrow">Evaluation</p><h2>What earns a place in a TTT system.</h2></div><div className="copy-section__body"><p>A strong specification sheet is not enough if the product is difficult to integrate, document, support or replace.</p><div className="evaluation-strip">{criteria.map(x=><span key={x}>{x}</span>)}</div></div></div></section>
 <section className="cta-band"><div className="shell cta-band__inner"><div><p className="eyebrow">Manufacturers + vendors</p><h2>Have technology TTT should evaluate?</h2></div><Link className="button button--light" href="/work-with-us">Work with TTT →</Link></div></section>
 </main>}
