import Link from 'next/link';
export const metadata={title:'Terms of Use & Service',description:'Website, product and service terms for Thompson Transportation Technologies LLC.'};
const updated='September 10, 2026';
export default function Page(){return <main className="legal-page"><section className="legal-hero"><div className="shell shell--legal"><p className="eyebrow">Legal</p><h1>Terms of Use & Service</h1><p className="lead">Terms governing use of the TTT website and the baseline rules for estimates, products and vehicle technology services.</p><p className="legal-updated">Last updated: {updated}</p></div></section><section className="section"><div className="shell shell--legal legal-copy">
  <h2>1. Agreement and scope</h2><p>These Terms apply to the website and services offered by Thompson Transportation Technologies LLC (“TTT,” “we,” “us,” or “our”). By using the website, you agree to these Terms. Specific estimates, work orders, product warranties, installation authorizations, subscriptions, return policies or commercial agreements may contain additional terms. If there is a conflict, the more specific written agreement controls for that transaction.</p>
  <h2>2. Website information is not a project authorization</h2><p>Website descriptions, compatibility information, educational content, example packages and pricing indications are general information. A project is not authorized until TTT and the customer agree to the applicable written scope, pricing and authorization. Vehicle-specific compatibility can depend on year, make, model, trim, factory options, software, prior modifications and physical inspection.</p>
  <h2>3. Estimates, diagnostics and additional work</h2><p>Estimates are based on the information reasonably available when prepared and remain subject to stated validity periods and assumptions. Diagnostic, inspection or disassembly charges should be disclosed before they are performed. TTT will seek customer approval before performing material additional work outside an authorized scope, except where immediate action is reasonably necessary to protect the vehicle or people and contacting the customer is impracticable.</p>
  <h2>4. Vehicle information and customer responsibilities</h2><p>You agree to provide information you reasonably believe is accurate, disclose known modifications or issues that could affect the work, remove valuables and personal items from relevant work areas, and ensure that you have authority to authorize work on the vehicle. Fleet and business customers are responsible for obtaining any notices, consents or permissions required before monitoring drivers, employees or other users through cameras, tracking or telematics.</p>
  <h2>5. Products, compatibility and substitutions</h2><p>Product specifications, availability, finish and compatibility may change. TTT may propose an equivalent or better substitute when an approved item is unavailable, but material substitutions require customer approval. Customer-supplied products may be accepted case by case and may involve different labor, diagnostic, return or warranty treatment.</p>
  <h2>6. Aftermarket products and vehicle warranties</h2><p>Use of an aftermarket part or independent service provider does not by itself automatically void a vehicle manufacturer's warranty. However, a manufacturer or dealer may deny warranty coverage for damage it can demonstrate was caused by an aftermarket product or improper installation. TTT does not control manufacturer warranty decisions and cannot guarantee how a third party will evaluate a future claim.</p>
  <h2>7. Connected products, software and subscriptions</h2><p>Tracking, remote-start, camera, cloud, telematics and connected services may depend on cellular coverage, GPS reception, internet access, third-party servers, manufacturer apps, firmware, account status and paid subscriptions. TTT does not guarantee uninterrupted availability of third-party services. Subscription prices and terms are controlled by the applicable provider unless TTT expressly states otherwise.</p>
  <h2>8. Security products</h2><p>Alarms, immobilization, kill-switch systems, cameras and tracking products reduce or manage risk but cannot guarantee that theft, loss, unauthorized access or damage will never occur. TTT will not publish or disclose customer-specific bypass locations or sensitive installation details except to authorized persons when appropriate.</p>
  <h2>9. Ecommerce, payment and taxes</h2><p>When online sales are activated, prices will be shown in U.S. dollars unless stated otherwise. Applicable taxes, shipping and other charges will be disclosed during checkout. Payment processing may be handled by third-party providers. Orders may be declined or canceled for suspected fraud, pricing errors, supply problems, legal restrictions or other legitimate reasons; when payment has been captured for a canceled order, an appropriate refund will be issued.</p>
  <h2>10. Shipping and delays</h2><p>For merchandise ordered online, TTT will provide shipment timing information based on information reasonably available at the time of sale. If merchandise cannot be shipped within the promised timeframe, or within the period required by applicable law when no timeframe is stated, TTT will provide the legally required delay/cancellation options and refunds. Services and installation appointments are not merchandise shipments.</p>
  <h2>11. Returns, manufacturer warranties and TTT workmanship</h2><p>Return eligibility may depend on product condition, installation status, special-order status, electronic activation, hygiene/safety considerations and manufacturer rules. Any written TTT workmanship warranty and any manufacturer product warranty will be made available with the relevant transaction. Nothing in these Terms is intended to waive rights that cannot lawfully be waived.</p>
  <h2>12. Scheduling, cancellations and vehicle pickup</h2><p>Appointment, deposit, cancellation, storage and pickup terms will be disclosed in the applicable estimate or work order. Completion dates are estimates unless expressly guaranteed in writing. Delays can result from parts availability, hidden prior modifications, diagnostics, third-party programming, weather or other circumstances outside reasonable control.</p>
  <h2>13. Intellectual property</h2><p>The TTT name, branding, website design, original articles, diagrams, photography, software and other TTT-created content are owned by TTT or used with permission and are protected by applicable intellectual-property laws. You may use public website content for personal, non-commercial reference but may not copy, republish, scrape, sell or create derivative commercial materials from it without permission.</p>
  <h2>14. User submissions</h2><p>If you submit photos, project details, reviews or other content, you represent that you have the right to provide it. TTT will not use identifiable customer project media for public marketing without appropriate permission. Reviews and testimonials must reflect genuine experience; TTT will not condition incentives on a positive review.</p>
  <h2>15. Acceptable use</h2><p>You may not misuse the website, attempt unauthorized access, interfere with security, introduce malicious code, harvest data, impersonate another person, or use TTT services or vehicle technology for unlawful surveillance, stalking, theft, evasion or other unlawful purposes.</p>
  <h2>16. Third-party links and services</h2><p>References to third-party brands, products or websites do not make TTT responsible for their content, availability, security, terms or privacy practices. A recommendation may reflect TTT's technical evaluation, but any material commercial relationship should be disclosed where it could affect how a reasonable customer interprets the recommendation.</p>
  <h2>17. Disclaimers and limitation of liability</h2><p>The website and general educational content are provided on an “as available” basis and are not a substitute for vehicle-specific inspection, professional diagnostics, legal advice or manufacturer instructions. To the maximum extent permitted by law, TTT is not liable for indirect, incidental, special, exemplary or consequential damages arising solely from use of the public website. Transaction-specific liability, warranty and remedy terms may be addressed in the applicable written agreement. These Terms do not exclude liability or consumer rights that cannot legally be excluded.</p>
  <h2>18. Governing law and disputes</h2><p>These Terms are governed by the laws of the State of Texas, without regard to conflict-of-laws principles. Unless a separate written agreement provides otherwise, disputes that cannot be resolved informally will be brought in a court of competent jurisdiction in Harris County, Texas, subject to any non-waivable right or venue rule under applicable law.</p>
  <h2>19. Changes and severability</h2><p>We may update these Terms as services change. Revised Terms apply prospectively from the posted effective date unless law requires otherwise. If a provision is unenforceable, the remaining provisions remain in effect to the extent permitted by law.</p>
  <h2>20. Contact</h2><p>Questions about these Terms can be submitted through the <Link href="/contact">Contact page</Link>.</p>
  <div className="legal-source-note"><h2>Legal framework used for this draft</h2><p>This draft was researched against Texas Attorney General automotive repair guidance, the Texas Deceptive Trade Practices Act framework, FTC warranty/Magnuson-Moss guidance, and the FTC Mail, Internet, or Telephone Order Merchandise Rule. Transaction documents should be reviewed by qualified Texas counsel before TTT begins taking commercial orders or vehicle-repair authorizations.</p></div>
</div></section></main>}
