export const servicePages = {
 'window-tint':{title:'Cooler cabin. Less glare. More privacy.',eyebrow:'Window Tint',seoTitle:'Ceramic Window Tint in Houston | TTT',meta:'Cooler cabin, less glare, more privacy. TTT helps you choose film for heat rejection, not just darkness, and installs it cleanly in Houston.',support:'The right film makes a Houston afternoon easier to live with. We help you choose it for heat rejection, not just darkness, then fit it cleanly to the glass you choose.',primary:'Request a Tint Quote',primaryHref:'/quote?service=tint',secondary:'Jump to darkness vs. heat ↓',secondaryHref:'#darkness-vs-heat',heroVisual:'tintHero',sections:[
  {title:'The short version',bullets:['Film type decides heat. Ceramic film targets infrared, the part of sunlight you feel as heat.','Shade decides privacy. Darkness is measured as VLT; a lower number is darker.','Darker isn’t cooler. A lighter ceramic film can keep a cabin cooler than a darker basic film.','The rules vary by window. We confirm what is permitted before film goes on.'],visual:'tintLayers'},
  {title:'Why people tint, and why they’re glad they did',bullets:['Heat: less heat building up through the glass, so the cabin cools faster.','UV: quality film can help protect skin and slow fading of seats and trim.','Glare: easier driving in low sun and bright conditions.','Privacy: passengers and belongings are less visible from outside.','Finish: an even shade can make the vehicle look complete.']},
  {id:'film-types',title:'Not all film is the same',table:[['Film','What it does','Worth knowing'],['Dyed','Darkens the glass','Entry-level; limited heat control'],['Carbon','Absorbs and blocks light','Stable matte look; better heat control than dyed'],['Ceramic','Targets infrared heat','Strong heat control without very dark glass; non-metallic, so unlikely to affect phone, GPS or radio signals']]},
  {id:'darkness-vs-heat',title:'Darker isn’t the same as cooler',body:['Darkness controls visible light. Most of the heat you feel is infrared, and film technology decides how much of it gets through. If you want a cooler cabin without a very dark look, choose the film first and the shade second.','VLT, or visible light transmission, is the share of visible light that passes through the glass and film together. Factory glass has its own tint, so the finished result depends on both.'],visual:'tintInstall'},
  {title:'Choose the glass',body:['Coverage can include front side windows, rear side windows, rear windshield, a windshield sun strip, full-windshield heat-control film where permitted, and sunroof or panoramic glass. We confirm the vehicle and glass before quoting.']},
  {title:'Clean glass, clean edges, checked in good light',steps:[['Confirm','Confirm windows, film and shade; inspect the glass for chips or old film.'],['Protect','Protect nearby panels and electronics from water.'],['Shape','Shape the film to each window.'],['Apply','Apply the film and work out water and air.'],['Inspect','Inspect edges, clarity and coverage before handover.']]},
  {title:'The first few days',bullets:['Keep windows up until the handover guidance says otherwise.','Slight haze or small water pockets can be normal while film cures.','Clean with a microfiber cloth and ammonia-free cleaner. Avoid blades or abrasive pads.','If you later see bubbling, peeling or discoloration, contact TTT.']},
  {title:'What we need for an accurate tint quote',body:['Year, make and model; the glass you want covered; whether old film is present; and what matters most: heat, privacy, looks or glare. Not sure about film? That is what the conversation is for.'],tessa:'Which tint is right for my vehicle?'}
 ],solutionLinks:[['Premium Vehicle Experience','/solutions/premium-vehicle-experience'],['Fleet & Dealership','/solutions/fleet-dealership']],faqs:[['Will tint make my car noticeably cooler?','It can, especially with film designed for heat rejection. Film type, the glass covered and how you use the car all affect the result.'],['Is ceramic worth the extra cost?','For drivers who spend long periods in the car or park in the sun, often yes. If privacy and looks matter most, another film may be enough.'],['What percentage should I choose?','It depends on privacy, night visibility and what is permitted on each window. We recommend options once we know the vehicle.'],['Will tint interfere with my phone, GPS or keyless entry?','Ceramic and carbon films are non-metallic and unlikely to affect signals.'],['How long does it take?','Timing depends on the vehicle, the glass being covered and whether old film has to be removed. Your quote will set expectations for the specific job.'],['Is there a warranty?','Product and workmanship terms are confirmed with the approved job rather than published as a blanket promise.']],finalTitle:'Ready to choose film and shade?',finalCopy:'Send the vehicle and the glass you have in mind. We’ll recommend options and explain what each one does.'},
 audio:{title:'Better sound, built around how you listen.',eyebrow:'Automotive Audio',seoTitle:'Car Audio Upgrades in Houston, Factory Features Kept | TTT',meta:'Better sound built around how you listen, without losing your factory screen, steering controls or alerts. Speakers, amplifiers, DSP tuning and custom installs in Houston.',support:'Clearer vocals, tighter bass and sound that seems to come from in front of you, without losing the factory screen, controls and alerts you use every day.',primary:'Request an Audio Quote',primaryHref:'/quote?service=audio',secondary:'Jump to upgrade paths ↓',secondaryHref:'#upgrade-paths',heroVisual:'audioHero',sections:[
  {title:'Upgrade the sound, not the problems',body:['Modern vehicles route audio through the same system as parking sensors, chimes, cameras and driver alerts. We look at how your factory system is built before recommending anything.'],bullets:['Keep the factory screen, CarPlay or Android Auto where practical.','Keep steering-wheel controls.','Keep warning, navigation and parking chimes.','Keep backup and surround cameras.','Where a feature cannot be kept, we tell you before you decide.'],tessa:'Can I keep my factory radio?',visual:'audioFlow'},
  {title:'What do you want to hear?',body:['Someone who wants podcasts clear on the highway needs a different system from someone who wants bass they can feel. We ask how you listen, what bothers you now, and how much space you are willing to give up.']},
  {id:'upgrade-paths',title:'Four common directions',body:['Starting points, not fixed packages. Every system is quoted to the vehicle.'],table:[['Path','Suits','Usually involves'],['Factory system improvement','Drivers who like their factory screen and want clearly better sound','Speakers, targeted sound treatment, sometimes a compact amplifier or processor'],['Balanced upgrade','Full, even sound across different music','Front speakers, amplifier, modest subwoofer, DSP and tuning'],['Bass-focused','Deep, strong low end','Subwoofer(s), dedicated power and a vehicle-specific enclosure'],['Complete custom system','A planned build from the ground up','Full speaker set, amplification, DSP, treatment, fabrication and extensive tuning']],visual:'audioPlacement'},
  {title:'Equipment sets the ceiling. Tuning decides what you hear.',body:['You sit off-center in a small space full of glass and plastic. A DSP adjusts timing, levels and frequency response so sound from every speaker arrives together and the stage sits in front of you rather than at your knee. We tune in the vehicle, from the listening position.']},
  {title:'Less rattle, cleaner sound',body:['Doors and panels are thin metal that vibrate and let road noise in. Sound treatment in the right places tightens midbass, reduces rattles and makes the cabin quieter on the highway.']},
  {title:'When the part doesn’t come in a box',body:['Speaker adapters, amplifier mounts and enclosures shaped to your trunk are often what separates a clean install from a compromised one. TTT can design and make them for your vehicle.'],links:[['See Custom Fabrication','/services/custom-fabrication']],visual:'audioComponents'}
 ],solutionLinks:[['Premium Vehicle Experience','/solutions/premium-vehicle-experience'],['Custom Integration','/solutions/custom-integration']],faqs:[['Can you upgrade my factory audio without replacing the screen?','Often, yes. Many vehicles take better speakers, amplification and processing while keeping the factory head unit.'],['Will I lose CarPlay or steering controls?','We plan to keep them and explain any known trade-off before work begins.'],['Do I need an amplifier?','Not always. For more volume with clarity, or a subwoofer, usually yes.'],['Will an upgrade drain my battery?','A correctly designed system should not. If you already have a drain problem, start with SignalTrace.'],['Can you fix a system another shop installed?','Often. We inspect it first and tell you what we find before recommending changes.'],['Can I upgrade in stages?','Yes. We plan so each stage builds on the last.']],finalTitle:'Let’s plan a system that fits your vehicle.',finalCopy:'Tell us what you drive, what you listen to and what you would change.'},
 'gps-tracking':{title:'Know where your vehicle is.',eyebrow:'GPS Tracking',seoTitle:'GPS Tracker Installation in Houston | TTT',meta:'Know where your vehicle is. Professionally installed GPS tracking with location, alerts and geofencing for personal and business vehicles in Houston.',support:'Location, alerts and trip history for one vehicle or several, installed out of sight and wired so it keeps reporting.',primary:'Request a Tracking Quote',primaryHref:'/quote?service=gps',secondary:'See Vehicle Security →',secondaryHref:'/solutions/vehicle-security',heroVisual:'gpsHero',sections:[
  {title:'Answers when you need them',body:['Most of the time a tracker sits quietly. It earns its place when a vehicle is not where it should be, a new driver is late home, or a work truck needs to be on site by eight.'],bullets:['Live location from your phone or computer.','Alerts you choose, such as movement, ignition or power disconnection, where the device supports them.','Geofencing: a virtual boundary that alerts you when the vehicle enters or leaves an area.','Trip history for where it went and when.','Several vehicles on one account, where the platform supports it.'],tessa:'What tracker would fit my use case?',visual:'gpsUseCases'},
  {title:'Who uses it',table:[['For','Typical use'],['Personal vehicles','Theft response, peace of mind while traveling, finding the car in a large lot'],['Families','Confirming a new driver arrived, checking a loaned vehicle'],['Stored or seasonal vehicles','An alert if a classic, trailer or project car moves'],['Business vehicles','Job-site arrival, routes and mileage, after-hours alerts']]},
  {title:'Hidden, powered properly, checked before handover',bullets:['Discretion: placement is chosen for each vehicle. We do not publish installation locations.','Reliable power: correct connections avoid battery drain and dropped reporting.','Verification: we confirm it reports and that alerts reach you before handover.'],visual:'gpsHardware'},
  {title:'Tracking shows where. A kill switch helps stop it moving.',body:['They do different jobs. Many owners choose both, and we plan them together so they do not conflict.'],links:[['See Kill Switches','/services/kill-switches']]},
  {title:'What tracking can’t promise',body:['Tracking gives you and law enforcement location information. It cannot guarantee a stolen vehicle will be recovered. TTT installs tracking only on vehicles the customer owns or is authorized to manage.']}
 ],solutionLinks:[['Vehicle Security','/solutions/vehicle-security'],['Connected Vehicle','/solutions/connected-vehicle'],['Fleet & Dealership','/solutions/fleet-dealership']],faqs:[['Is professional installation better than a plug-in tracker?','Plug-in devices are easy to find and remove. A professionally installed tracker is harder to find and can be powered more reliably.'],['Will a tracker drain my battery?','A correctly installed tracker draws very little power while parked. If your battery already drains, see SignalTrace.'],['Is there a monthly fee?','That depends on the platform selected. Subscription terms are confirmed before you approve the system.'],['Will it guarantee I get my vehicle back?','No. It provides location information; recovery depends on factors outside the tracker.'],['Can I track several vehicles on one account?','Often, depending on the platform. Tell us about all the vehicles before we choose hardware.'],['Can I track a vehicle I do not own?','Only if you are authorized to act for the owner.'],['Where will you put it?','We choose a location for each vehicle and keep it confidential.']],finalTitle:'Set up tracking that works when it matters.',finalCopy:'Tell us about the vehicle or vehicles and what you want to know about them.'},
 'kill-switches':{title:'Make unauthorized use harder.',eyebrow:'Kill Switches / Immobilization',seoTitle:'Kill Switch & Immobilizer Installation in Houston | TTT',meta:'Make unauthorized use harder. A professionally integrated kill switch adds an independent barrier to starting or driving your vehicle, planned for Houston drivers.',support:'An independent barrier between a thief and your vehicle’s ignition, integrated so it does not create new electrical problems and simple enough to live with every day.',primary:'Request a Security Consultation',primaryHref:'/quote?service=kill-switch',secondary:'See Vehicle Security →',secondaryHref:'/solutions/vehicle-security',heroVisual:'securityHero',sections:[
  {title:'Another lock, independent of the factory one',body:['A kill switch, or immobilization solution, stops the vehicle starting or running unless an authorized condition is met. Most modern vehicles already have a factory immobilizer; an aftermarket one adds a separate layer, so getting past the factory system is no longer enough.','We do not describe methods or installation locations publicly. Keeping them private is part of what makes them work.'],visual:'securityComponents'},
  {title:'Worth considering if…',bullets:['Your model is frequently targeted, or you have had a theft or attempt.','The vehicle is parked on the street or in open lots.','It is a work vehicle carrying tools or equipment.','It is a classic or specialty vehicle that would be hard to replace.'],body:['It may suit you less if many people share the vehicle, or if a particular approach is not compatible with its electronics. We will say so.']},
  {title:'Installed so it doesn’t cause new problems',body:['An immobilizer sits on circuits the vehicle needs to start and run. Done badly, it can cause intermittent no-starts and warning lights that are difficult to trace later. We assess the vehicle, choose an approach that fits how you use it, integrate carefully, confirm normal starting and running, and show you how to use it at handover.'],links:[['Already have one causing trouble? See SignalTrace','/services/signaltrace']]},
  {title:'One layer, not the whole answer',body:['No single device makes a vehicle theft-proof. A kill switch makes it harder to drive away; tracking helps you find it if something happens. Planned together, they do not conflict.'],links:[['See GPS Tracking','/services/gps-tracking']],tessa:'What’s the difference between tracking and immobilization?',visual:'securityLayers'},
  {title:'It starts with a private conversation',body:['Tell us the vehicle, where it is parked and what security it already has. We explain options and trade-offs, you approve the plan, and we install and verify. Details of your setup are not shared.']}
 ],solutionLinks:[['Vehicle Security','/solutions/vehicle-security'],['Fleet & Dealership','/solutions/fleet-dealership']],faqs:[['Will a kill switch stop my car being stolen?','It makes theft harder. No device can promise to prevent it.'],['My car has a factory immobilizer. Do I need another?','Not necessarily. An independent layer helps if the factory system is bypassed. Whether it is worthwhile depends on the vehicle and how it is used.'],['Will it be a hassle every day?','We choose an approach that fits your routine. Most owners find it quickly becomes habit.'],['Can other people drive the car?','Yes, once you show them how.'],['Will it affect my manufacturer warranty?','We can explain exactly what the installation involves so you can check the implications with your manufacturer or dealer.'],['Where do you install it?','We do not publish installation details.']],finalTitle:'Talk through your vehicle’s security.'},
 signaltrace:{title:'Find the cause of the electrical problem.',eyebrow:'TTT SignalTrace™ · Advanced Vehicle Electronics Diagnostics',seoTitle:'Car Electrical Problem Diagnosis in Houston | TTT SignalTrace™',meta:'Find the cause of the electrical problem. SignalTrace traces battery drain, intermittent no-starts and module faults to a documented root cause, one approved stage at a time.',theme:'When the problem isn’t obvious, trace it.',support:'For faults that come and go, batteries that keep dying, and problems that have already been through a code reader and a parts counter. Five stages, each approved before it starts, each documented.',primary:'Start a SignalTrace Intake',primaryHref:'/quote?service=signaltrace',secondary:'Jump to the five stages ↓',secondaryHref:'#method',heroVisual:'signalHero',heroTessa:'My battery keeps dying.',sections:[
  {title:'Sound familiar?',bullets:['“It’s been to two shops and nobody can find it.”','“It only happens sometimes, never when I take it in.”','“They replaced the battery and it’s dead again.”','“It started after something was installed.”','“There’s a code, but fixing what it pointed to didn’t help.”'],body:['That is the situation SignalTrace was built for.']},
  {id:'method',title:'Five stages. Evidence at every step.',table:[['Stage','What happens','What it rules in or out'],['Scan','Your history, stored and pending codes, live data','Where to look first'],['Isolate','Tests separate the systems involved from those that are not','Which system or circuit'],['Trace','Follow the circuit or network through voltage drop, grounds, connectors, wiring and module behavior','The physical cause'],['Verify','Confirm the cause explains the symptoms and reproduce the fault where possible','That the repair is aimed at the right thing'],['Resolve','Repair after approval, then retest under the conditions that caused it','That the fault is gone and nothing else was disturbed']],visual:'signalProcess'},
  {title:'Problems SignalTrace is for',table:[['Area','Examples'],['Power and battery','Parasitic drain, batteries that keep going flat, charging concerns'],['Starting','Intermittent no-start or no-crank, security-related start inhibits'],['Body electronics','Powered steps, lighting, windows, locks and accessories acting unpredictably'],['Security conflicts','Alarm false triggers, remote-start conflicts, GPS or immobilizer issues'],['Networks and modules','Communication faults, modules dropping offline, several unrelated warning lights'],['Wiring and grounds','Damaged or corroded wiring, poor grounds, repairs that did not hold'],['Previous aftermarket work','Problems that began after audio, lighting, security or accessory installs']],visual:'signalNetwork'},
  {title:'Codes are evidence, not the answer',body:['A code scan is useful and it is where SignalTrace starts. But a code often names the module that noticed a problem, not the cause. Intermittent faults can vanish before the vehicle reaches a shop, and one failure can show up as a symptom somewhere else on the network. Replacing the part a code points to can cost money without fixing anything.']},
  {title:'You stay in control of time and cost',steps:[['Intake','Symptoms, timing, conditions, previous repairs and aftermarket equipment.'],['Review','We confirm SignalTrace is the right approach before you commit.'],['Approved diagnostic block','Time is approved before testing begins.'],['Check-in','If more time is needed, we explain what we found and what we would test next. You decide.'],['Findings','The cause, or what has been ruled out, and our recommendation.'],['Repair','Quoted and approved separately. You can take the findings elsewhere.'],['Proof','Retest after repair under the conditions that caused the fault.']]},
  {title:'A written record, whatever the outcome',body:['You receive a record of symptoms and conditions, codes and data recorded, tests performed and measurements, what was ruled out and why, the confirmed or most likely cause, and the recommended next step.'],visual:'signalTools'}
 ],solutionLinks:[['Vehicle Security','/solutions/vehicle-security'],['Custom Integration','/solutions/custom-integration'],['Fleet & Dealership','/solutions/fleet-dealership']],faqs:[['How is this different from a diagnostic scan?','A scan reads codes. SignalTrace uses them as evidence, then isolates, traces and verifies to find the physical cause.'],['Can you guarantee you will find it?','No one can honestly guarantee that. We can promise a structured method, clear check-ins and a record of what was tested.'],['How much does it cost?','Diagnostic time is approved in stages, so you control how far it goes. The current rate and authorization structure are confirmed before work begins.'],['What if the fault does not happen while you have the car?','Common with intermittent faults. Your history helps, and the plan can be built around the conditions that trigger it.'],['What if you cannot find the cause?','You still receive the record of what was tested and ruled out, which narrows the problem for whoever works on it next.'],['My battery keeps dying. Is that SignalTrace?','If a new battery has not fixed it, often yes. Parasitic drain is one of the most common cases.'],['Can you diagnose another shop’s installation?','Yes. Aftermarket integration faults are a core part of SignalTrace.'],['Do I need to describe it in technical terms?','No. Tell us what you notice, when, and what you have tried.']],finalTitle:'Tell us what your vehicle is doing.',finalCopy:'The more we know about the symptoms, the better the first stage can be planned.'},
 'custom-fabrication':{title:'Make the part that doesn’t exist.',eyebrow:'Custom Fabrication & Additive Manufacturing',seoTitle:'Custom Automotive Brackets & 3D-Printed Parts | TTT Houston',meta:'Make the part that does not exist. Custom mounts, brackets, adapters, switch panels and enclosures designed, prototyped and fitted to your vehicle in Houston.',support:'Mounts, brackets, adapters and enclosures designed around your vehicle and your equipment, then refined until they fit properly.',primary:'Start a Project Inquiry',primaryHref:'/quote?service=fabrication',secondary:'Jump to the process ↓',secondaryHref:'#process',heroVisual:'fabricationHero',heroTessa:'I need a mount that doesn’t exist.',sections:[
  {title:'Universal parts rarely fit universally',body:['The equipment is right, but there is no good way to mount it. Universal brackets leave gaps and rattle. The original part was discontinued. The space was never designed for what you want to add. A part made for the job solves it, and it looks like it belongs.']},
  {title:'What we make',bullets:['Brackets for amplifiers, processors and accessories.','Mounts for devices, displays and controls.','Speaker adapters for non-standard openings.','Switch panels that integrate controls into the interior.','Enclosures that protect modules and wiring.','Prototype pieces to test an idea first.','Trim pieces that fill gaps or replace hard-to-find parts.'],body:['Not on the list? Ask. Many projects start with “I’m not sure this is possible.”'],visual:'fabricationExamples'},
  {id:'process',title:'From problem to fitted part',table:[['Step','What happens'],['Define','What the part must do, where it goes and what it connects to'],['Design','A digital model built to the vehicle and equipment dimensions'],['Prototype','A first version to check shape and size'],['Fit','Tested in place on the vehicle'],['Refine','Adjusted until fit, finish and function are right'],['Produce','Made in a material suited to where it will live']],visual:'fabricationProcess'},
  {title:'3D printing as a practical tool',body:['Printing builds a part layer by layer from the design. For vehicles, the value is practical: parts follow complex curves, fit tight spaces and can be revised quickly after a test fit. One-offs and short runs do not need expensive tooling. Materials are chosen for the environment where the part will live.']},
  {title:'What we don’t make',body:['Fabrication covers mounting, integration, interior and electronics parts. We do not make safety-critical or structural components, including anything related to braking, steering, suspension, seat belts, airbags or load-bearing structure.']}
 ],solutionLinks:[['Custom Integration','/solutions/custom-integration'],['Premium Vehicle Experience','/solutions/premium-vehicle-experience'],['Fleet & Dealership','/solutions/fleet-dealership']],faqs:[['Can you make a part from a photo?','A photo is a good start. We usually need measurements or the vehicle to get the fit right.'],['Can you copy a broken or discontinued part?','Often, if it is not safety-critical.'],['Are printed parts strong enough?','For the right applications, yes. Material and design are matched to the job, heat and location.'],['Will they survive Houston heat?','Materials are selected around the environment where the part will live.'],['Can you make more than one?','Yes. A proven design can be reproduced, which is useful for fleets.']],finalTitle:'Have a part in mind that doesn’t exist yet?',finalCopy:'Tell us what it needs to do and where it goes. Rough measurements are fine.'}
};

export const faqGroups=[
 ['Quality',[['How do you check the work before I pick up the vehicle?','We test what we installed or repaired, then recheck the factory functions it could have affected. Exactly what is checked depends on the job.'],['What does good installation quality mean?','Mostly things you will not see: secure connections, sensible routing, protection from heat and movement, correct fusing and access for future service.'],['Will you take panels off my car?','Often, yes. They are removed and refitted with care, and we plan the job so they come off as few times as possible.']]],
 ['Timing & Delivery',[['How long will my vehicle be with you?','It depends on the vehicle, the work, parts availability and whether existing work needs removing first. The estimate sets expectations for the specific job.'],['What happens at handover?','We show you what was done, explain how to use anything new and give you any relevant care instructions.'],['Can a job take longer than planned?','Sometimes. Hidden previous work, damaged trim or a part delay can change timing. If it does, we tell you why and what happens next before going further.']]],
 ['Warranty & Support',[['What happens if you find something unexpected?','We stop and talk to you. Nothing is added to the scope or the bill without your approval.'],['What warranty applies?','Product warranties depend on the manufacturer. TTT workmanship or support terms are stated with the approved job rather than invented as a blanket website promise.'],['What if I notice a problem after pickup?','Contact us with the vehicle, the work done and what you are seeing. Photos or the conditions that trigger it can help.'],['Will you work on equipment another shop installed?','Often. We start by understanding what is there. If it is causing faults, SignalTrace is usually the right route.']]],
 ['Quotes & Pricing',[['How do I get a quote?','Use the Request a Quote form, contact us or ask Tessa to start one.'],['Does a quote commit me to anything?','No.'],['Why don’t you publish prices?','Glass, audio architecture, wiring and fitment vary enough by vehicle that a list price can be misleading. A short form gets you a vehicle-specific answer.'],['What affects the price?','The vehicle, products selected, labor, removal of previous work and parts availability.']]],
 ['Your Vehicle',[['Do you work on my make and model?','TTT works across makes and models. We confirm fit and compatibility once we know the vehicle.'],['Will this affect my manufacturer warranty?','We explain what the installation involves so you can check any vehicle-specific implications with your manufacturer or dealer.'],['Can parts be hard to get?','Sometimes, especially for newer or less common vehicles. We tell you when we quote.']]],
 ['Privacy',[['Can I have a tracker put on a vehicle I don’t own?','Only if you are authorized to act for the owner.'],['Who knows where my security devices are?','You do. We do not publish or share installation details.'],['What do you do with my information?','We use it to respond to your request and operate the service. See the Privacy Policy for details.']]],
 ['Window Tint',[['Does darker tint block more heat?','Not necessarily. Film technology matters more than darkness.'],['What does the tint percentage mean?','VLT is the share of visible light that passes through. Lower is darker.'],['How do I care for new tint?','Follow the handover curing guidance, then use microfiber and ammonia-free cleaner.']]],
 ['Audio',[['Can I keep my factory radio?','In many vehicles, yes.'],['What is tuning?','Adjusting timing, balance and frequency response so the system sounds right from your seat.']]],
 ['Tracking & Security',[['What is the difference between a tracker and a kill switch?','A tracker helps you find the vehicle. A kill switch makes it harder to drive away.'],['Will a tracker drain my battery?','Not when correctly selected and installed.']]],
 ['SignalTrace',[['Is SignalTrace just a code scan?','No. The scan is the first of five stages. SignalTrace uses the result as evidence, then isolates, traces, verifies and resolves.'],['What do I get at the end?','A written summary of what was tested, what was found and what is recommended next.']]],
 ['Fabrication',[['What can you make?','Mounts, brackets, adapters, panels and enclosures. Not safety-critical or structural parts.'],['What do you need from me?','What the part must do, photos and any measurements you have.']]]
];
