export const learnTopics={
dsp:{slug:'dsp',eyebrow:'Learn · Technology · Audio',seoTitle:'DSP & Automotive Audio Signal Processing | TTT',meta:'Why automotive DSP matters, what it controls and why factory signal processing has to be understood before an audio upgrade is designed.',h1:'DSP is control over the signal, not more volume.',hero:'A digital signal processor can correct, route and time the audio signal for the actual cabin. It cannot fix a system that was never understood in the first place.',question:'Why doesn’t more amplifier power automatically make a car sound better?',shortAnswer:'Because power only makes the existing signal louder. If the factory signal is already equalized, split, delayed or limited, those decisions travel downstream until a processor measures and corrects them.',heroVisual:'audioFlow',primary:'See Automotive Audio',primaryHref:'/services/audio',secondary:'Read the DSP deep dive',secondaryHref:'/articles/how-dsp-changes-modern-car-audio',sections:[
 {title:'Start with the factory signal',body:['Many modern systems shape the audio before it reaches the speakers. Equalization, crossovers, volume-dependent bass reduction, time alignment and separate amplifier channels can all be part of the factory strategy. An upgrade has to know what is already happening before it adds anything.']},
 {title:'What a DSP controls',bullets:['Signal summing: rebuilding a full-range signal when the factory divides it among several channels.','Equalization: correcting tonal peaks and dips from the source and the cabin.','Crossovers: sending each speaker only the frequencies it is meant to play.','Time alignment: delaying the nearest speakers so sound reaches the listening position together.','Level and routing: matching channels and directing the right signal to the right amplifier and speaker.']},
 {title:'The vehicle is part of the system',body:['Speaker placement, glass, seats, trim and the fact that the driver sits off-center all change what reaches your ears. That is why tuning happens in the vehicle, from the listening position, rather than from a product spec sheet.'],links:[['How to plan a factory audio upgrade','/articles/how-to-plan-factory-audio-upgrade']]}
],finalTitle:'Understand the signal before choosing the parts.'},
'oem-integration':{slug:'oem-integration',eyebrow:'Learn · Technology · OEM Integration',seoTitle:'OEM Vehicle Technology Integration | TTT',meta:'How aftermarket technology can be added while preserving factory screens, controls, alerts, cameras and serviceability.',h1:'The vehicle is already a system. Added equipment has to join it.',hero:'Screens, controls, alerts, microphones, cameras, amplifiers and data networks can all be connected. Good integration starts by identifying what must keep working.',question:'Can I add technology without losing factory features?',shortAnswer:'Often, yes. The right interface depends on the exact vehicle and trim, and the plan begins with the factory functions that must be preserved.',heroVisual:'homeHeroTechnical',primary:'Read The TTT Standard',primaryHref:'/standards',secondary:'Check Vehicle Fitment',secondaryHref:'/vehicles',sections:[
 {title:'Preserve first',body:['Before choosing hardware, list the factory features the customer relies on: screen, steering controls, chimes, microphones, backup or surround cameras, parking sensors, phone integration and vehicle settings. Then design the added system around those requirements.']},
 {title:'Four integration questions',bullets:['Signal: where does the useful audio, trigger or status signal come from?','Power: which source can safely support the added equipment without disturbing sleep behavior?','Data: does the function depend on CAN, LIN, A2B, MOST or another vehicle network?','Control: how should the driver activate or adjust the new capability without adding unnecessary clutter?']},
 {title:'OEM+ is a result',body:['OEM+ is not a brand of parts. It describes an outcome: the added capability looks deliberate, behaves predictably, respects the vehicle’s systems, remains serviceable and leaves a clear record of what changed.'],links:[['What OEM+ actually means','/articles/what-oem-plus-integration-means']]}
],finalTitle:'Preserve what works. Improve what matters.'},
telematics:{slug:'telematics',eyebrow:'Learn · Technology · Telematics',seoTitle:'Vehicle Telematics & GPS Tracking Explained | TTT',meta:'How vehicle tracking works from GPS device to cellular network, cloud platform, alerts, subscriptions and user access.',h1:'A tracker is only as useful as the path from the vehicle to your screen.',hero:'A tracking system is a chain: device, power, GPS, cellular network, cloud platform, app and user access. Each link has to work for the information to be useful.',question:'What am I actually paying for with a tracker?',shortAnswer:'Not just the box under the dash. You are paying for a connected service: hardware, network access, a platform that stores and interprets the data, and the app or dashboard you use.',heroVisual:'gpsUseCases',primary:'See GPS Tracking',primaryHref:'/services/gps-tracking',secondary:'See Connected Vehicle',secondaryHref:'/solutions/connected-vehicle',sections:[
 {title:'Vehicle → GPS → cellular → cloud → screen',body:['GPS tells the device where it is. Cellular sends that information out of the vehicle. The cloud platform stores history and creates alerts. The app or dashboard decides what the user can actually see and do.']},
 {title:'Questions that matter before installation',bullets:['Who needs access, and from which devices?','Which alerts are useful enough that they will not simply be muted?','How long does the vehicle sit, and how should the device behave while parked?','What subscription is required and what happens if it ends?','Who owns the account and the location history?']},
 {title:'One vehicle and a fleet are different problems',body:['A single owner may only need location and a few alerts. A fleet may need roles, reports, vehicle history and a lifecycle process for hardware moving in and out of service. The platform should match the use case.'],links:[['What to ask before installing a GPS tracker','/articles/what-to-ask-before-installing-gps-tracker']]}
],finalTitle:'Choose the connected system, not just the device.'},
'vehicle-vision':{slug:'vehicle-vision',eyebrow:'Learn · Technology · Vehicle Vision',seoTitle:'Vehicle Cameras & Vision Systems Explained | TTT',meta:'How to think about vehicle cameras: coverage, storage, parking mode, power and footage retrieval. Educational content; not currently a primary TTT service.',h1:'A camera system is defined by what it covers and what you can retrieve.',hero:'Resolution is easy to compare on a box. The harder questions are what the camera sees, when it records, how it is powered and whether the footage is available when you actually need it.',question:'What makes vehicle camera footage useful when something happens?',shortAnswer:'The right coverage, dependable recording, enough storage, a safe power strategy and a retrieval process you can use under pressure.',heroVisual:'technologyDetail',primary:'See Connected Vehicle',primaryHref:'/solutions/connected-vehicle',secondary:'Browse the Technology Library',secondaryHref:'/technology',sections:[
 {title:'Start with the event',body:['Forward road events, rear impacts, cabin activity and parking events are different recording problems. Decide which event matters before choosing lenses and channel count.']},
 {title:'Five system questions',bullets:['Coverage: which directions or spaces must be visible?','Trigger: continuous recording, ignition, movement, impact or parking event?','Power: how does parking mode avoid creating battery problems?','Storage: how much history is kept before older footage is overwritten?','Retrieval: can the useful clip be found, exported and shared quickly?']},
 {title:'A Learn topic, not a service promise',body:['TTT is keeping Vehicle Vision in the Technology Library until the camera offering, installation approach, pricing and support model are confirmed. Education can be useful without pretending a commercial service exists today.']}
],finalTitle:'Start with the event you need to see.'},
brands:{slug:'brands',eyebrow:'Learn · Brands & Technology Partners',seoTitle:'How TTT Chooses Products and Brands | Thompson Transportation Technologies',meta:'How TTT evaluates film, audio, tracking and integration products: vehicle fit, reliability, documentation, support, warranty handling and value.',h1:'We choose products for the vehicle, not the logo.',hero:'Every product we recommend has to fit the vehicle, work with what is already there and be supportable after the install. Brand matters, but only as part of that.',question:'How should I judge a product beyond the spec sheet?',shortAnswer:'Start with fit, reliability, documentation, installer support, warranty handling and whether the product solves the actual customer problem.',heroVisual:'technologyHero',primary:'Read The TTT Standard',primaryHref:'/standards',secondary:'Ask about a specific product',secondaryHref:'/contact',sections:[
 {title:'Six things we look for',bullets:['Vehicle fit: compatible with the exact vehicle, trim and factory system, not merely “universal.”','Reliability: able to handle heat, vibration and daily vehicle use.','Documentation: wiring, settings and specifications that can be verified.','Installer support: a supplier or manufacturer that can answer technical questions.','Warranty and returns: a clear process if hardware fails.','Customer value: the right capability for the goal, not the longest feature list.']},
 {title:'The category changes the criteria',body:['Window film is judged on optical quality, heat performance and stability. Audio products have to fit the signal path and the listening goal. Tracking adds network, platform and subscription questions. Integration modules have to preserve factory behavior. Fabrication materials have to match heat, load and finish.']},
 {title:'What we publish, and what we do not',bullets:['A brand is named only when TTT approves it for publication.','Authorized dealer, certified installer or partner language is used only when the relationship is current and verified.','Brand logos appear only with permission.','If you ask for a specific product, we will say whether it fits the vehicle and why we would or would not recommend it.']}
],finalTitle:'Fit and support come before the badge.'}
};