export const solutionPages={
 'premium-vehicle-experience':{title:'Premium Vehicle Experience',h1:'Upgrades that feel like they came with the car.',seoTitle:'Premium Vehicle Upgrades, Planned as One | TTT Houston',meta:'Tint, audio and in-car technology planned together so the finished vehicle feels complete, not modified. Factory features kept, one scope, one handover.',hero:'A cooler, quieter cabin with better sound and technology you will actually use, planned as one job so it works with the car rather than on top of it.',heroVisual:'solutionPremium',primary:'Request a Premium Vehicle Quote',primaryHref:'/quote?solution=premium',secondary:'Jump to what’s included ↓',secondaryHref:'#services-involved',sections:[
  {title:'For drivers who plan to keep the car',bullets:['You have just bought a vehicle and want it right from the start.','The factory sound, heat or glare bothers you every day.','You have seen upgrades that look bolted on and want the opposite.','You would rather do it once than add things piecemeal over three years.']},
  {title:'Separate upgrades rarely add up to a better car',body:['Tint from one shop, audio from another and accessories added later can each be fine on their own. Together they often mean panels removed several times, trim that never quite sits right, a dash full of adapters and factory features that quietly stopped working. The car ends up more modified, not more complete.']},
  {title:'What changes when it’s planned as one',table:[['You notice','Because'],['The cabin stays cooler and calmer','Film is chosen for heat rejection, and panels can receive sound treatment while they are open'],['Music sounds like it is in front of you','The system is tuned from the driver’s seat'],['Nothing you liked is gone','Factory screen, controls, chimes and cameras are planned around, not over'],['Nothing looks added','Mounts and panels are made for the vehicle where off-the-shelf will not fit'],['One conversation, one handover','One scope, one schedule, one walkthrough at the end']]},
  {id:'services-involved',title:'Services involved',table:[['Service','Its role in the result'],['Window Tint','Heat, glare, UV and privacy'],['Automotive Audio','Sound quality with factory features kept'],['Custom Fabrication','Clean mounting and fitment'],['GPS Tracking (optional)','Peace of mind for a vehicle worth protecting']],links:[['Window Tint','/services/window-tint'],['Automotive Audio','/services/audio'],['Custom Fabrication','/services/custom-fabrication'],['GPS Tracking','/services/gps-tracking']]},
  {title:'The details that decide whether it feels factory',bullets:['Panels off once. Work is sequenced so trim is disturbed as little as possible.','One power plan. Added electronics share a properly planned, fused supply instead of competing for it.','Controls that make sense. New functions use factory controls where practical rather than adding clutter.'],links:[['What OEM+ means to TTT','/articles/what-oem-plus-vehicle-integration-means']]},
  {title:'What to expect',steps:[['Tell us','The vehicle, how you use it and what bothers you now.'],['Plan','A recommended combination, what each part does and any trade-offs.'],['Approve','One scope for the whole job. It can be phased if you prefer.'],['Do the work','Sequenced so the vehicle is disturbed as little as possible.'],['Check and hand over','New systems tested, factory functions rechecked, then a walkthrough of what changed.']]}
 ],faqs:[['Do I have to do everything at once?','No. We can plan the whole path and do it in phases so nothing needs redoing later.'],['Will it void my factory warranty?','We explain exactly what the work involves so you can check vehicle-specific implications with your dealer or manufacturer.'],['Is there a package price?','Every vehicle is quoted individually because glass, audio architecture and fitment vary.']],finalTitle:'Tell us about the car and what you would change.',finalCopy:'Concept One shows the reference approach; your vehicle determines the actual plan.'},
 'vehicle-security':{title:'Vehicle Security',h1:'Harder to take. Easier to find.',seoTitle:'Layered Vehicle Security in Houston | TTT',meta:'Harder to take, easier to find. TTT plans immobilization and GPS tracking together around where your vehicle is parked and how it is used.',hero:'Layered protection planned around your vehicle, where it is parked and who drives it, so it adds real difficulty for a thief without making life difficult for you.',heroVisual:'solutionSecurity',primary:'Request a Security Consultation',primaryHref:'/quote?solution=security',secondary:'Jump to the layers ↓',secondaryHref:'#layers',sections:[
  {title:'Who it is for',bullets:['Your model is one thieves target.','The vehicle sleeps on the street, in an open lot or at a job site.','It carries tools, equipment or something you cannot easily replace.','You have had a theft, an attempt or a break-in and want to act.']},
  {title:'One device answers one question',body:['A tracker tells you where the vehicle went after it is gone. A factory immobilizer can be bypassed by someone who knows the model. Each layer covers one moment. Relying on any single one leaves the others open.']},
  {id:'layers',title:'Each layer covers a different moment',table:[['Moment','Layer','What it does','Service'],['Before','Deter','Visible signs of protection and good parking habits reduce opportunity','Consultation'],['During','Immobilize','An independent barrier to starting or driving','Kill Switches'],['During','Alert','Movement, ignition or power alerts where the platform supports them','GPS Tracking'],['After','Locate','Location and history to support recovery','GPS Tracking'],['Ongoing','Keep it working','Faults in existing security traced and fixed','SignalTrace™']]},
  {title:'Security that works together, and doesn’t break the car',bullets:['No conflicts. Tracker and immobilizer are planned so one does not disable or drain the other.','No new faults. Poorly installed security can cause intermittent no-starts; normal starting and running are verified before handover.','Nothing published. Methods and locations stay private.','Simple for you. The routine fits how you use the vehicle and who else drives it.'],tessa:'What’s the difference between tracking and immobilization?'},
  {title:'What to expect',steps:[['Tell us','The vehicle, where it is parked, what happened if anything, and what is already fitted.'],['Plan','A recommended combination of layers and what each one will and will not do.'],['Approve','One scope, in private.'],['Do the work','Installed discreetly.'],['Check and hand over','Starting, running and alerts confirmed; you are shown how to use it.']],body:['No combination makes a vehicle theft-proof. The aim is to make yours meaningfully harder to take and easier to find.']}
 ],faqs:[['Which layer should I start with?','It depends on the risk. Frequently targeted vehicles often start with immobilization; recovery-focused owners with tracking.'],['Do you install on vehicles I do not own?','Tracking is installed only for owners or people authorized to act for them.'],['My current security is causing problems. Can you help?','Yes. SignalTrace diagnoses security and remote-start conflicts.']],finalTitle:'Talk through your vehicle’s security in private.'},
 'connected-vehicle':{title:'Connected Vehicle',h1:'Know what your vehicle is doing when you’re not in it.',seoTitle:'Connected Vehicle Tracking & Alerts in Houston | TTT',meta:'Know what your vehicle is doing when you are not in it. TTT helps choose the right tracking platform and alerts, then installs the hardware cleanly and verifies it reports.',hero:'The right information, on the right person’s phone, from hardware that is installed out of sight and keeps reporting. Not another app you will stop opening.',heroVisual:'solutionConnected',primary:'Request a Connected Vehicle Quote',primaryHref:'/quote?solution=connected',secondary:'Jump to choosing a setup ↓',secondaryHref:'#choose',sections:[
  {title:'Who it is for',table:[['You','You want to know'],['A family with several drivers','That a new driver got there, where a shared car is'],['Owner of a stored or seasonal vehicle','If a classic, trailer or project car moves'],['Frequent traveler','That the car is still where you parked it'],['Small business with a few vehicles','Arrivals, routes and after-hours use']]},
  {title:'Most connected setups fail quietly',body:['A plug-in tracker gets unplugged. An app sends so many alerts everyone mutes it. A device is wired to a circuit that drains the battery. The subscription lapses and nobody notices. The hardware was never the hard part. Deciding what is worth knowing, and installing it so it keeps working, is.']},
  {id:'choose',title:'Decide what’s worth knowing, then make it reliable',steps:[['What do you need to know?','Location, movement, arrivals, after-hours use.'],['Who should know it?','You, a partner or a manager. Access is set up for the people who need it.'],['How quickly?','Live, or a summary may be enough.'],['Which platform?','Features, app and subscription terms are compared before you approve.']],body:['The result: alerts you actually read, on hardware that stays connected.']},
  {title:'Services involved',table:[['Service','Role'],['GPS Tracking','Location, alerts, geofencing and history'],['Kill Switches (optional)','Turns knowing into being able to stop unauthorized use'],['Custom Fabrication (as needed)','Clean mounting for in-cabin hardware'],['SignalTrace™ (as needed)','Finding drains or faults from previous devices']],links:[['GPS Tracking','/services/gps-tracking'],['Kill Switches','/services/kill-switches'],['Custom Fabrication','/services/custom-fabrication'],['SignalTrace','/services/signaltrace']]},
  {title:'Why integration matters',bullets:['Power that does not drain: devices draw from the right circuit and are correctly fused.','Out of sight, not out of service: hidden placement that still gets a signal.','Verified reporting: location and alerts reach the right phones before handover.','Ready to grow: the platform can take another vehicle later without starting again.'],tessa:'What tracker would fit my use case?'},
  {title:'What to expect',steps:[['Tell us','The vehicles, who uses them and what you want to know.'],['Plan','A recommended platform and alert setup, including ongoing costs.'],['Approve','Hardware, installation and subscription terms stated up front.'],['Do the work','Discreet installation, wired for reliability.'],['Check and hand over','Reporting and alerts tested on your phone; access set up for the people you name.']],body:['TTT installs tracking only on vehicles the customer owns or is authorized to manage.']}
 ],faqs:[['Can more than one person see the vehicle?','Usually yes, depending on the platform. We set up access for the people you choose.'],['Will I be flooded with alerts?','Not if we set them up around what you actually need to know. That is part of the planning.'],['What does it cost each month?','Subscription terms depend on the selected platform and are confirmed before approval.']],finalTitle:'Tell us what you would like to know about your vehicle.'},
 'fleet-dealership':{title:'Fleet & Dealership',h1:'The same result on every vehicle.',seoTitle:'Fleet & Dealership Vehicle Technology Installation | TTT Houston',meta:'The same result on every vehicle. Tracking, security, tint and electronics installed to a written standard, recorded per vehicle, with one point of contact.',hero:'Vehicle technology installed to a written standard, recorded vehicle by vehicle, and managed through one point of contact, so the tenth install matches the first.',heroVisual:'solutionFleet',businessInquiry:true,primary:'Start a Business Inquiry',primaryHref:'#inquiry',secondary:'For dealerships ↓',secondaryHref:'#dealerships',sections:[
  {title:'Good installs don’t scale by accident',body:['One well-installed vehicle proves an installer can do the work. Twenty vehicles prove whether they can do it the same way every time. Without a written standard, placement drifts, wiring varies, nobody knows which device is in which vehicle, and every support call starts from scratch.']},
  {title:'Repeatability you can check',table:[['Deliverable','What it means for you'],['A written install standard per vehicle type','Equipment, placement approach, power and connections agreed before the first vehicle'],['A record for every vehicle','VIN or unit number, what was installed, device IDs and settings, date and checks passed'],['Verification on every unit','Each vehicle tested before it is returned, not a sample'],['One point of contact','One place for scheduling, questions and records'],['Reusable parts','Custom mounts designed once and reproduced for every matching vehicle'],['Support that starts with facts','If a unit has a problem later, the record shows what is in it']]},
  {id:'dealerships',title:'Accessories that fit the sales and delivery process',body:['Dealer programs work when the product, the sales conversation and the installation are designed together. TTT can help turn individual installs into defined packages that sales, service and delivery teams can understand and repeat.'],bullets:['Packages defined by model, trim or customer need, instead of an open parts list.','Tint, tracking and security fitted consistently to inventory or sold units.','Installation planned around delivery schedules.','A clean handover so the customer sees a finished vehicle.']},
  {id:'fleets',title:'Standardize the program before the hardware',body:['Fleet technology has to survive vehicles being added, reassigned, repaired and retired. We plan the program first: who needs which information, which platform owns it and what each vehicle type receives. Then the hardware is installed the same way on every unit.'],bullets:['Tracking selected for your reporting and user roles.','Immobilization where theft or unauthorized use is a risk.','Diagnostics for vehicles already in service with electrical problems.','Records that follow each vehicle through its life.']},
  {title:'Services involved',body:['GPS Tracking · Kill Switches · Window Tint · SignalTrace™ · Custom Fabrication · Automotive Audio for dealer packages.']},
  {title:'What to expect',steps:[['Tell us','Vehicle types, quantities, locations and what you want to achieve.'],['Plan','A proposed standard and a pilot vehicle.'],['Approve','The standard, per-vehicle scope and schedule.'],['Do the work','Pilot first, then the program to the approved standard.'],['Check and hand over','Every unit verified and recorded.']]}
 ],faqs:[['Can you start with one vehicle?','Yes. A pilot vehicle is the recommended start.'],['Do you offer volume pricing?','Pricing is discussed once the scope is clear.'],['Can you install equipment we supply?','That is reviewed case by case as part of the program scope.']],finalTitle:'Start a conversation about your vehicles.',finalCopy:'A few details help us come back with a useful first response. Nothing here commits you.'},
 'custom-integration':{title:'Custom Integration',h1:'When what you need doesn’t come in a kit.',seoTitle:'Custom Vehicle Electronics Integration in Houston | TTT',meta:'When what you need does not come in a kit. TTT defines the requirement, designs the system, fabricates what is missing and documents the result.',hero:'Unusual factory electronics, limited space, several systems that have to work together, or a requirement nobody makes a product for. We define it, design it, build what is missing and document how it works.',heroVisual:'solutionCustom',primary:'Start a Custom Project',primaryHref:'/quote?solution=custom',secondary:'Jump to how a project runs ↓',secondaryHref:'#project',sections:[
  {title:'Projects that start with “is this even possible?”',bullets:['A work truck that needs controls for equipment the factory never planned for.','A vehicle whose factory electronics defeat off-the-shelf kits.','A previous install that needs to be untangled and redone properly.','A multi-system build that needs custom mounting, controls or interfaces.']},
  {title:'Generic hardware forced into a specific vehicle',body:['When there is no kit, the temptation is to adapt the closest one: splice into whatever wire works, mount it wherever it fits, and hope nothing interacts badly. The result can work on day one and become a diagnostic problem a year later.']},
  {title:'A system designed for your requirement',bullets:['It does what you asked without compromises caused by the wrong hardware.','It looks deliberate, with panels and mounts made for the space.','The rest of the car still works because factory functions were mapped first.','Someone can service it later because it is documented.']},
  {title:'Services involved',table:[['Service','Role'],['Custom Fabrication','Mounts, panels and enclosures for the actual space'],['SignalTrace™','Mapping existing electronics and untangling previous work'],['Automotive Audio, GPS Tracking, Kill Switches','Whichever systems the project includes']],links:[['Custom Fabrication','/services/custom-fabrication'],['SignalTrace','/services/signaltrace']]},
  {id:'project',title:'How a project runs',table:[['Step','What happens','What you get'],['Tell us','The requirement in your words; photos help','A first conversation, no commitment'],['Plan','Inputs, outputs, power, controls, space and failure modes defined','A written plan and estimate'],['Approve','You sign off the plan','A fixed scope'],['Do the work','Build, fabricate, integrate, often with test fits along the way','Updates at agreed points'],['Check and hand over','Every function tested; factory systems rechecked','A walkthrough and a record of how it is built']]},
  {title:'Design first. Build second.',body:['Most integration problems are decided before a tool comes out: which signal to use, where power comes from, what happens if something fails. Spending time there is what makes the result reliable and serviceable.'],tessa:'I need a mount that doesn’t exist.'}
 ],faqs:[['Can you take on a project another shop started?','Often. We start by mapping what is there before recommending anything.'],['How is a custom project priced?','Every project is scoped individually once the requirement is clear.'],['What won’t you do?','Anything safety-critical or structural, or anything that would make a vehicle unsafe or non-compliant.']],finalTitle:'Bring us the requirement.',finalCopy:'Describe what you need the vehicle to do. We will tell you honestly whether we can help.'}
};
export const solutionList=Object.entries(solutionPages).map(([slug,page])=>({slug,...page}));
