'use client';
import { useState } from 'react';
import VehicleSelector from '../../components/VehicleSelector';
import { capabilityLabels } from '../../lib/vehicles';

export default function VehiclesPage(){
 const [vehicle,setVehicle]=useState({}); const name=[vehicle.year,vehicle.make,vehicle.model,vehicle.trim].filter(Boolean).join(' ');
 return <main><section className="page-hero"><div className="shell"><p className="eyebrow">Vehicle compatibility</p><h1>Start with the vehicle. Build the technology around it.</h1><p className="lead">Choose a vehicle to create a shared context for compatible systems, products, projects and future TTT recommendations.</p></div></section><section className="section section--soft"><div className="shell vehicle-hub"><div className="vehicle-hub__panel"><p className="eyebrow">My vehicle</p><h2>Select a vehicle</h2><VehicleSelector compact onChange={setVehicle}/><p className="form-note">This is the Phase 2 compatibility foundation. Full VIN decoding and trim-level fitment data will connect to the vehicle database in a later integration wave.</p></div><div className="vehicle-hub__result"><p className="eyebrow">TTT vehicle profile</p><h2>{name||'Your selected vehicle'}</h2><p>{name?'TTT can now use this vehicle as context across solutions, projects and the future shop experience.':'Select a year, make and model to preview its technology profile.'}</p><div className="compatibility-grid">{capabilityLabels.map(([a,b])=><article key={a}><b>{a}</b><small>{b}</small></article>)}</div><div className="mini-specs"><div><span>Profile status</span><strong>{name?'Ready':'Awaiting vehicle'}</strong></div><div><span>Compatibility</span><strong>Database-ready</strong></div><div><span>TTT garage</span><strong>Planned</strong></div></div>{name&&<div className="button-row"><a className="button button--light" href="/start">Start a project →</a><a className="button button--ghost-dark" href="/shop">Explore shop</a></div>}</div></div></section></main>
}
