import Link from 'next/link';
import AssetMedia from '../../components/AssetMedia';
import InquiryForm from '../../components/InquiryForm';

export const metadata={title:'Fleet & Dealership Vehicle Technology in Houston | TTT',description:'Consistent tracking, security and electronics installation for dealerships, fleets and automotive businesses in Houston.'};

const audiences=[
 ['Dealerships','Accessory and security installations on inventory or sold units, with consistent results you can offer customers with confidence.'],
 ['Independent automotive businesses','A technical partner for specialized tracking, immobilization, electronics integration or difficult electrical faults.'],
 ['Commercial vehicle operators','Contractors, service companies and delivery operators that need visibility and protection across vehicles and equipment.'],
 ['Small fleets','Groups of vehicles that need tracking, security or upgrades installed consistently.']
];

export default function Page(){return <main className="production-page">
 <section className="review-hero review-hero--compact"><AssetMedia visual="fleetReal" className="review-hero__media" priority/><div className="review-hero__overlay"/><div className="shell review-hero__copy"><p className="eyebrow">Fleet & Dealership Solutions</p><h1>Vehicle technology for fleets and dealerships</h1><p className="lead lead--dark">Tracking, security and electronics work installed the same way on every vehicle, documented, and handled through one point of contact.</p><a className="button" href="#business-inquiry">Start a Business Inquiry →</a></div></section>
 <section className="section"><div className="shell"><div className="section-heading"><div><p className="eyebrow">Who we can support</p><h2>Built for businesses that depend on vehicles</h2></div></div><div className="principle-grid">{audiences.map(([t,b],i)=><article key={t}><small>0{i+1}</small><h3>{t}</h3><p>{b}</p></article>)}</div></div></section>
 <section className="section section--soft"><div className="shell copy-section__grid"><div><p className="eyebrow">Consistency</p><h2>The tenth vehicle should match the first</h2></div><div className="copy-section__body"><p>When you are equipping more than one vehicle, consistency affects reliability, maintenance and how easily your team can use what is installed.</p><ul className="clean-list"><li>Agree a standard before repeat work begins.</li><li>Document what was installed on each vehicle.</li><li>Verify every unit before it returns to service.</li><li>Reuse validated fabricated parts when the vehicle and requirement repeat.</li></ul></div></div></section>
 <section className="section section--dark"><div className="shell editorial-media-band"><AssetMedia visual="gpsUseCases"/><div><p className="eyebrow">Tracking & security</p><h2>Visibility and protection across your vehicles</h2><p>Tracking shows where vehicles are and how they are used. Immobilization adds a barrier to unauthorized use. We help decide what each vehicle needs rather than applying the same answer blindly across a mixed fleet.</p><p>Tracking is installed only on vehicles the customer or business owns or is authorized to manage.</p></div></div></section>
 <section className="section"><div className="shell copy-section__grid"><div><p className="eyebrow">Custom requirements</p><h2>Have something specific in mind?</h2></div><div className="copy-section__body"><p>Some projects do not fit a standard service: a control panel for a work truck, a mounting solution for specialist equipment, or an integration problem across a mixed fleet. Tell us what you are trying to achieve and we will tell you honestly whether we can help.</p><div className="button-row"><Link className="button button--ghost" href="/services/gps-tracking">GPS Tracking</Link><Link className="button button--ghost" href="/services/signaltrace">SignalTrace</Link><Link className="button button--ghost" href="/services/custom-fabrication">Fabrication</Link></div></div></div></section>
 <section id="business-inquiry" className="section section--soft"><div className="shell contact-form-grid"><div><p className="eyebrow">Business inquiry</p><h2>Start a conversation about your vehicles</h2><p>Share a few details and the TTT team can follow up to discuss scope and next steps. Unconfirmed claims about volume pricing, on-site service or service-level agreements are intentionally not published in this review build.</p></div><InquiryForm type="business" title="Send Business Inquiry" intro="Tell us about the organization, vehicles and technology requirement."/></div></section>
 <section className="cta-band"><div className="shell cta-band__inner"><div><p className="eyebrow">Fleet & Dealership</p><h2>Let’s talk about your vehicles.</h2></div><a className="button button--light" href="#business-inquiry">Start a Business Inquiry →</a></div></section>
 </main>}
