import Link from 'next/link';
export const metadata={title:'Accessibility',description:'Accessibility statement for Thompson Transportation Technologies LLC.'};
const updated='September 10, 2026';
export default function Page(){return <main className="legal-page"><section className="legal-hero"><div className="shell shell--legal"><p className="eyebrow">Legal</p><h1>Accessibility Statement</h1><p className="lead">TTT wants its digital experience to remain usable as the site becomes more visual, interactive and technically sophisticated.</p><p className="legal-updated">Last updated: {updated}</p></div></section><section className="section"><div className="shell shell--legal legal-copy">
  <h2>Our commitment</h2><p>Thompson Transportation Technologies LLC is committed to providing digital experiences that are accessible to people with disabilities. Accessibility is treated as an ongoing product-quality requirement, not a one-time overlay.</p>
  <h2>Accessibility target</h2><p>Our current target is the Web Content Accessibility Guidelines (WCAG) 2.2 Level AA. WCAG provides testable criteria for perceivable, operable, understandable and robust web content. This is an ongoing effort; TTT does not claim that every page or third-party integration currently achieves full WCAG 2.2 AA conformance.</p>
  <h2>What we are building for</h2><ul><li>Keyboard-accessible navigation and controls.</li><li>Visible focus indicators.</li><li>Semantic page structure and labels compatible with assistive technologies.</li><li>Text alternatives for meaningful non-text content.</li><li>Sufficient text contrast and information that is not communicated by color alone.</li><li>Touch targets and controls suitable for mobile and tablet use.</li><li>Zoom and text-resizing support without unnecessary loss of content.</li><li>Captions or transcripts for important prerecorded media when applicable.</li><li>Reduced-motion support and non-cinematic alternatives for motion-heavy experiences.</li><li>Accessible forms with labels, instructions and error/status feedback.</li></ul>
  <h2>Cinematic and 3D experiences</h2><p>TTT's public website is designed to include interactive vehicle visualizations and cinematic motion. Those experiences should not become the only way to access essential information. We intend to provide equivalent text/content paths, honor reduced-motion preferences where practical, and avoid trapping keyboard or assistive-technology users inside decorative experiences.</p>
  <h2>Third-party content</h2><p>Some future ecommerce, payment, mapping, video, manufacturer or connected-service interfaces may be operated by third parties. TTT will work to select and configure vendors with accessibility in mind, but we do not control every aspect of third-party products.</p>
  <h2>Feedback and assistance</h2><p>If you encounter an accessibility barrier, use our <Link href="/contact">Contact page</Link> and select “Accessibility feedback.” Please include the page or feature, the issue you encountered, and the assistive technology/browser/device if you are comfortable sharing it. We will use that information to investigate and prioritize remediation.</p>
  <h2>Assessment and improvement</h2><p>Accessibility should be reviewed during design, development and content publishing, supplemented by automated checks and periodic manual keyboard/screen-reader testing. Significant new components — especially My TTT, TTT OS, Shop and 3D/cinematic experiences — should be tested before being treated as production-complete.</p>
  <div className="legal-source-note"><h2>Standards used for this statement</h2><p>This statement was developed with reference to U.S. Department of Justice guidance on web accessibility and the ADA, and the W3C Web Content Accessibility Guidelines 2.2. DOJ guidance recognizes that businesses open to the public must ensure equal access to goods and services offered online, while W3C recommends WCAG 2.2 as the current web accessibility standard.</p></div>
</div></section></main>}
